### ISSUE TITLE
Develop branch won't startup

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/SickRage#1008]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop/748e455c7228c219dbb42af630d0a23e9979c4d6
OS: Debian8
What you did: Restarted through init.d
What happened: Exception, and was not started
What you expected:
Logs:
```
root@OMV:/opt/medusa# /etc/init.d/sickrage restart
Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/local/python/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/home/opt/medusa/sickbeard/logger.py", line 171, in format
    msg = super(CensoredFormatter, self).format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 468, in format
    s = self._fmt % record.__dict__
KeyError: u'curhash'
Logged from file parser.py, line 241
Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/local/python/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/home/opt/medusa/sickbeard/logger.py", line 171, in format
    msg = super(CensoredFormatter, self).format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 468, in format
    s = self._fmt % record.__dict__
KeyError: u'curhash'
Logged from file parser.py, line 241
Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/local/python/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/home/opt/medusa/sickbeard/logger.py", line 171, in format
    msg = super(CensoredFormatter, self).format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 468, in format
    s = self._fmt % record.__dict__
KeyError: u'curhash'
Logged from file parser.py, line 241

```

**Comment by ratoaq2** [comment]
Fixed by #945
