### ISSUE TITLE
[APP SUBMITTED]: ParseError: unclosed token: line 104, column 12

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#1066]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Commit**: PyMedusa/SickRage@c6c6e8412f45c591f4257bd4bceeca84261c2913
**Link to Log**: https://gist.github.com/390d7bed2edf3e1a87218df470c99203
### ERROR
<pre>
2016-09-10 04:37:02 ERROR    SHOWQUEUE-REFRESH :: [c6c6e84] 269750: Error while refreshing show Wayward Pines. Error: unclosed token: line 104, column 12
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/show_queue.py#L581">sickbeard/show_queue.py</a>", line 581, in run
    self.show.update_metadata()
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/tv.py#L547">sickbeard/tv.py</a>", line 547, in update_metadata
    self.__update_show_nfo()
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/tv.py#L555">sickbeard/tv.py</a>", line 555, in __update_show_nfo
    result = cur_provider.update_show_indexer_metadata(self) or result
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/metadata/generic.py#L273">sickbeard/metadata/generic.py</a>", line 273, in update_show_indexer_metadata
    showXML = etree.ElementTree(file=xmlFileObj)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 611, in __init__
    self.parse(file)
  File "<string>", line 38, in parse
ParseError: unclosed token: line 104, column 12
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
No idea how to fix this

**Comment by medariox** [comment]
Fixed in https://github.com/pymedusa/SickRage/pull/1081

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [feature/indexer/tmdb](../tree/feature/indexer/tmdb)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@d4746eaedd0553bf2e0b4bcdea7c5fea9eaf51e3
**Link to Log**: https://gist.github.com/c583e39c907f70050f7bb052c7fe5811
### ERROR
<pre>
2016-11-14 22:40:16 ERROR    SEARCHQUEUE-BACKLOG-77904 :: [d4746ea] Checking AniDB scene exceptions update failed for Billboard Music Awards. Error: unclosed token: line 24537, column 2
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/d4746eaedd0553bf2e0b4bcdea7c5fea9eaf51e3/medusa/scene_exceptions.py#L335">medusa/scene_exceptions.py</a>", line 335, in _get_anidb_exceptions
    anime = adba.Anime(None, name=show.name, tvdbid=show.indexerid, autoCorrectName=True)
  File "/home/home/SickRage/<a href="../blob/d4746eaedd0553bf2e0b4bcdea7c5fea9eaf51e3/lib/adba/aniDBAbstracter.py#L123">lib/adba/aniDBAbstracter.py</a>", line 123, in __init__
    self.tvDBMap = TvDBMap()
  File "/home/home/SickRage/<a href="../blob/d4746eaedd0553bf2e0b4bcdea7c5fea9eaf51e3/lib/adba/aniDBtvDBmaper.py#L32">lib/adba/aniDBtvDBmaper.py</a>", line 32, in __init__
    self.xmlMap = fileInfo.read_tvdb_map_xml(filePath)
  File "/home/home/SickRage/<a href="../blob/d4746eaedd0553bf2e0b4bcdea7c5fea9eaf51e3/lib/adba/aniDBfileInfo.py#L124">lib/adba/aniDBfileInfo.py</a>", line 124, in read_tvdb_map_xml
    return read_xml_into_etree(filePath)
  File "/home/home/SickRage/<a href="../blob/d4746eaedd0553bf2e0b4bcdea7c5fea9eaf51e3/lib/adba/aniDBfileInfo.py#L132">lib/adba/aniDBfileInfo.py</a>", line 132, in read_xml_into_etree
    return etree.ElementTree(file=f)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 611, in __init__
    self.parse(file)
  File "<string>", line 38, in parse
ParseError: unclosed token: line 24537, column 2
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
