### ISSUE TITLE
[APP SUBMITTED]: ValueError: time data '16-07-16 23:09' does not match format '%Y-%m-%d %H:%M'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#1102]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Commit**: PyMedusa/SickRage@9b461cdcdb3f9c16e446475c9272dcd466d7f6aa
**Link to Log**: https://gist.github.com/239ad724cd193a7104eace89efb8fa5b
### ERROR
<pre>
2016-09-14 10:18:33 ERROR    POSTPROCESSOR :: [9b461cd] Failed Unrar archive the.getaway.car.s01e08.720p.hdtv-norite.rar: time data '16-07-16 23:09' does not match format '%Y-%m-%d %H:%M'
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/9b461cdcdb3f9c16e446475c9272dcd466d7f6aa/sickbeard/processTV.py#L460">sickbeard/processTV.py</a>", line 460, in unRAR
    rar_handle.extract(path=path, withSubpath=False, overwrite=False)
  File "/home/home/SickRage/<a href="../blob/9b461cdcdb3f9c16e446475c9272dcd466d7f6aa/lib/unrar2/__init__.py#L158">lib/unrar2/__init__.py</a>", line 158, in extract
    return RarFileImplementation.extract(self, checker, path, withSubpath, overwrite)
  File "/home/home/SickRage/<a href="../blob/9b461cdcdb3f9c16e446475c9272dcd466d7f6aa/lib/unrar2/unix.py#L210">lib/unrar2/unix.py</a>", line 210, in extract
    for info in self.infoiter():
  File "/home/home/SickRage/<a href="../blob/9b461cdcdb3f9c16e446475c9272dcd466d7f6aa/lib/unrar2/__init__.py#L120">lib/unrar2/__init__.py</a>", line 120, in infoiter
    for params in RarFileImplementation.infoiter(self):
  File "/home/home/SickRage/<a href="../blob/9b461cdcdb3f9c16e446475c9272dcd466d7f6aa/lib/unrar2/unix.py#L179">lib/unrar2/unix.py</a>", line 179, in infoiter
    data['datetime'] = time.strptime(fields[2]+" "+fields[3], '%Y-%m-%d %H:%M')
  File "/usr/lib/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '16-07-16 23:09' does not match format '%Y-%m-%d %H:%M'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Most probably upstream issue. We should move to rarfile asap.

**Comment by fernandog** [comment]
@medariox i remember we patched rar lib to fix this. Just check history

**Comment by medariox** [comment]
It's unrar2 and if we need to patch it, it means the time has come to use a different library to handle rar files: rarlib for example.

**Comment by medariox** [comment]
Ancient, unsupported Python version.
