### ISSUE TITLE
Error while submitting issue and while starting medusa

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#1105]
@ratoaq2 
```
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 269, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/server/web/core/error_logs.py", line 138, in submit_errors
    results = self.issue_submitter.submit_github_issue(CheckVersion())
  File "/home/osmc/SickRage/sickbeard/issuesubmitter.py", line 170, in submit_github_issue
    return IssueSubmitter.submit_issues(github, github_repo, loglines, similar_issues)
  File "/home/osmc/SickRage/sickbeard/issuesubmitter.py", line 194, in submit_issues
    gist = IssueSubmitter.create_gist(github, logline)
  File "/home/osmc/SickRage/sickbeard/issuesubmitter.py", line 54, in create_gist
    return github.get_user().create_gist(False, {'sickrage.log': InputFileContent(content)})
  File "/home/osmc/SickRage/lib/github/AuthenticatedUser.py", line 473, in create_gist
    input=post_parameters
  File "/home/osmc/SickRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/home/osmc/SickRage/lib/github/Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/osmc/SickRage/lib/github/Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/home/osmc/SickRage/lib/github/Requester.py", line 275, in __requestRaw
    requestHeaders
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1204, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
timeout: timed out
```

**Comment by ratoaq2** [comment]
So, it might be the log upload takes some time

**Comment by fernandog** [comment]
Got this while starting Medusa:
```
Traceback (most recent call last):
  File "SickBeard.py", line 564, in <module>
    medusa.start()
  File "SickBeard.py", line 312, in start
    sickbeard.initialize(consoleLogging=self.console_logging)
  File "/home/osmc/SickRage/sickbeard/__init__.py", line 710, in initialize
    authenticate(GIT_USERNAME, GIT_PASSWORD)
  File "/home/osmc/SickRage/sickbeard/github_client.py", line 28, in authenticate
    gh.get_rate_limit()
  File "/home/osmc/SickRage/lib/github/MainClass.py", line 135, in get_rate_limit
    '/rate_limit'
  File "/home/osmc/SickRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/home/osmc/SickRage/lib/github/Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/osmc/SickRage/lib/github/Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/home/osmc/SickRage/lib/github/Requester.py", line 275, in __requestRaw
    requestHeaders
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1204, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.timeout: timed out

```

**Comment by fernandog** [comment]
got this error again while starting medusa. Wtf is wrong with internet today?

**Comment by ratoaq2** [comment]
This shouldn't happen anymore after #1116

**Comment by fernandog** [comment]
thanks
