### ISSUE TITLE
SHOWQUEUE-REFRESH - Error: 'charmap' codec can't encode character issue

### ISSUE THREAD

**Issue by whipcracker** [pymedusa/SickRage#1161]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master - 61fc790112a85da0a487a930ec3c0d2c0511ac1f
OS: Win 10 Pro x64
What you did: Nothing lol
What happened: These errors popped up
What you expected: To not have errors, tbh.
Logs: Yes?
Hoping someone can make sense of the issue I'm also happening... seems to have happened around the same time that my other issue I just submitted happened as well.
```
2016-09-21 04:08:18 ERROR    SHOWQUEUE-REFRESH :: [61fc790] 248742: Error while refreshing show Person of Interest. Error: 'charmap' codec can't encode character u'\u03c0' in position 69: character maps to 
Traceback (most recent call last):
  File "C:\Medusa\sickbeard\show_queue.py", line 565, in run
    self.show.refresh_dir()
  File "C:\Medusa\sickbeard\tv.py", line 1267, in refresh_dir
    self.load_episodes_from_dir()
  File "C:\Medusa\sickbeard\tv.py", line 582, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(ek(os.path.join, self.location, media_file))
  File "C:\Medusa\sickbeard\tv.py", line 818, in make_ep_from_file
    'normal', 'anime')[self.is_anime]).parse(filepath)
  File "C:\Medusa\sickbeard\name_parser\parser.py", line 240, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Medusa\sickbeard\name_parser\parser.py", line 361, in __str__
    return helpers.canonical_name(obj, fmt='{key}: {value}', separator=', ')
  File "C:\Medusa\sickbeard\helpers.py", line 1655, in canonical_name
    return str(separator.join([fmt.format(key=k, value=v) for k, v in guess.items() if k not in ignore_list]))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u03c0' in position 69: character maps to 
2016-09-21 04:05:06 ERROR    SHOWQUEUE-REFRESH :: [61fc790] 248736: Error while refreshing show Grimm. Error: 'charmap' codec can't encode character u'\u0301' in position 59: character maps to 
Traceback (most recent call last):
  File "C:\Medusa\sickbeard\show_queue.py", line 565, in run
    self.show.refresh_dir()
  File "C:\Medusa\sickbeard\tv.py", line 1267, in refresh_dir
    self.load_episodes_from_dir()
  File "C:\Medusa\sickbeard\tv.py", line 582, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(ek(os.path.join, self.location, media_file))
  File "C:\Medusa\sickbeard\tv.py", line 818, in make_ep_from_file
    'normal', 'anime')[self.is_anime]).parse(filepath)
  File "C:\Medusa\sickbeard\name_parser\parser.py", line 240, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Medusa\sickbeard\name_parser\parser.py", line 361, in __str__
    return helpers.canonical_name(obj, fmt='{key}: {value}', separator=', ')
  File "C:\Medusa\sickbeard\helpers.py", line 1655, in canonical_name
    return str(separator.join([fmt.format(key=k, value=v) for k, v in guess.items() if k not in ignore_list]))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0301' in position 59: character maps to 
```

**Comment by ratoaq2** [comment]
This issue is the same of #1159 
We will keep you posted as soon as a fix is released. 
Thanks for reporting it.

**Comment by ratoaq2** [comment]
This is fixed in develop as well. We'll be testing for some time before releasing it
