### ISSUE TITLE
More charmap issues after last update on develop

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/SickRage#1174]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop
OS: windows
What you did: slept
What happened: woke up and saw errors
What you expected: to not see errors
Logs:
```
2016-09-23 09:37:53 ERROR    SEARCHQUEUE-BACKLOG-296389 :: [Zooqle] :: [cc2875f] Unknown exception while searching Zooqle. Error: u'charmap : title: The Romeo Section, season: 1, year: 2015, format: WEBRip, release_group: 720\xd1\u20ac.|.ViruseProject, type: episode, absolute_episode: [], quality: Unknown, episode: [] : error 83 : error 84 : character maps to '
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 212, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 239, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0440' in position 83: character maps to 
2016-09-23 08:48:20 ERROR    SEARCHQUEUE-BACKLOG-75682 :: [Torrentz2] :: [cc2875f] Unknown exception while searching Torrentz2. Error: 'Error binding parameter 7 - probably unsupported type.'
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 360, in find_search_results
    db.mass_action(cl)
  File "C:\SickRageMedusa\**********\db.py", line 212, in mass_action
    sql_results.append(self._execute(qu[0], qu[1], fetchall=fetchall))
  File "C:\SickRageMedusa\**********\db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
InterfaceError: Error binding parameter 7 - probably unsupported type.
2016-09-23 08:48:20 ERROR    SEARCHQUEUE-BACKLOG-75682 :: [Torrentz2] :: [cc2875f] DB error: InterfaceError('Error binding parameter 7 - probably unsupported type.',)
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
InterfaceError: Error binding parameter 7 - probably unsupported type.
2016-09-23 08:19:18 ERROR    SEARCHQUEUE-BACKLOG-299845 :: [Zooqle] :: [cc2875f] Unknown exception while searching Zooqle. Error: u'charmap : title: Doctor Foster, season: 1, year: 2015, format: HDTV, release_group: 720\xd1\u20ac.|.L2, type: episode, absolute_episode: [], quality: Unknown, episode: [] : error 77 : error 78 : character maps to '
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 212, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 239, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0440' in position 77: character maps to 
2016-09-23 07:33:14 ERROR    SEARCHQUEUE-BACKLOG-248835 :: [Zooqle] :: [cc2875f] Unknown exception while searching Zooqle. Error: u'charmap : title: Once Upon a Time, season: 1, year: [2011, 2012], format: WEBRip, release_group: Generalfilm.|.\xd0\u0161\xd0\u0178\xd0\u0161.|.D, type: episode, absolute_episode: [], quality: Unknown, episode: [] : error 101 : error 104 : character maps to '
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 212, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 239, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 101-103: character maps to 
2016-09-23 07:28:41 ERROR    SEARCHQUEUE-BACKLOG-248835 :: [Torrentz2] :: [cc2875f] Unknown exception while searching Torrentz2. Error: u'charmap : title: Once Upon A Time, season: 1, episode_title: \xd0\xbd\xd0\xb5\xd0\xb2\xd0\xb0\xd1\u201e\xd0\xb8\xd0\xbb\xd1\u0152\xd0\xbc, type: episode, absolute_episode: [], quality: Unknown, episode: [] : error 51 : error 60 : character maps to '
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 212, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 239, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 51-59: character maps to 
2016-09-23 07:01:23 ERROR    SEARCHQUEUE-BACKLOG-292174 :: [Zooqle] :: [cc2875f] Unknown exception while searching Zooqle. Error: u'charmap : title: Dark Matter, year: 2016, format: WEBRip, release_group: Kaztorrents.|.\xd0\u0161\xd0\u0178\xd0\u0161.|.LostFilm, type: episode, absolute_episode: [], quality: Unknown, episode: [], season: None : error 77 : error 80 : character maps to '
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 212, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 239, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 77-79: character maps to 
2016-09-23 07:00:55 ERROR    SEARCHQUEUE-BACKLOG-292174 :: [Torrentz2] :: [cc2875f] Unknown exception while searching Torrentz2. Error: u'charmap : title: Dark Matter, season: 2, format: WEBRip, year: 2016, episode_title: \xd0\xbe\xd1\u201a Kaztorrents, type: episode, absolute_episode: [], quality: Unknown, episode: [] : error 74 : error 76 : character maps to '
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 212, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 239, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 74-75: character maps to 
2016-09-23 06:18:37 ERROR    SEARCHQUEUE-BACKLOG-281714 :: [Zooqle] :: [cc2875f] Unknown exception while searching Zooqle. Error: u'charmap : title: Ballers, year: 2016, format: HDTV, release_group: Kaztorrents.|.\xd0\u0161\xd0\u0178\xd0\u0161.|.Amedia, type: episode, absolute_episode: [], quality: Unknown, episode: [], season: None : error 71 : error 74 : character maps to '
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 212, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 239, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 71-73: character maps to 
2016-09-23 05:43:26 ERROR    SEARCHQUEUE-BACKLOG-164501 :: [Torrentz2] :: [cc2875f] Unknown exception while searching Torrentz2. Error: u'charmap : title: Mike and Molly, season: 1, episode: [11], episode_title: \xd0\xb518, language: ru, type: episode, absolute_episode: [], quality: Unknown : error 64 : error 65 : character maps to '
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 212, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 239, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0435' in position 64: character maps to 
2016-09-23 05:08:26 ERROR    SEARCHQUEUE-BACKLOG-168571 :: [Zooqle] :: [cc2875f] Unknown exception while searching Zooqle. Error: 'Error binding parameter 7 - probably unsupported type.'
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 360, in find_search_results
    db.mass_action(cl)
  File "C:\SickRageMedusa\**********\db.py", line 212, in mass_action
    sql_results.append(self._execute(qu[0], qu[1], fetchall=fetchall))
  File "C:\SickRageMedusa\**********\db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
InterfaceError: Error binding parameter 7 - probably unsupported type.
2016-09-23 05:08:26 ERROR    SEARCHQUEUE-BACKLOG-168571 :: [Zooqle] :: [cc2875f] DB error: InterfaceError('Error binding parameter 7 - probably unsupported type.',)
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\db.py", line 108, in _execute
    sql_results = self.connection.cursor().execute(query, args)
InterfaceError: Error binding parameter 7 - probably unsupported type.
2016-09-23 05:05:19 ERROR    SHOWQUEUE-REFRESH :: [cc2875f] 269641: Error while refreshing show Chicago P.D.. Error: u'chicago.pd.s03e08.Forget.My.Name.720p.hdtv.hevc.x265.rmteam'
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\show_queue.py", line 566, in run
    self.show.refresh_dir()
  File "C:\SickRageMedusa\**********\tv.py", line 1266, in refresh_dir
    self.load_episodes_from_dir()
  File "C:\SickRageMedusa\**********\tv.py", line 598, in load_episodes_from_dir
    parse_result = NameParser(show=self, try_indexers=True).parse(ep_file_name)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 237, in parse
    name_parser_cache.add(name, result)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 415, in add
    del self._previous_parsed[self._previous_parsed.keys()[0]]
KeyError: u'chicago.pd.s03e08.Forget.My.Name.720p.hdtv.hevc.x265.rmteam'
2016-09-23 05:01:35 ERROR    SEARCHQUEUE-BACKLOG-248741 :: [Torrentz2] :: [cc2875f] Unknown exception while searching Torrentz2. Error: u'charmap : title: 2 Broke Girls, season: 5, episode: [2], episode_title: \xe4\xb8\xad\xe8\u2039\xb1\xe5\xad\u2014\xe5\xb9\u2022, other: HR, format: HDTV, audio_codec: AAC, screen_size: 576p, video_codec: h264, container: mp4, mimetype: video/mp4, type: episode, absolute_episode: [], quality: SDTV : error 62 : error 66 : character maps to '
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 212, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 239, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 62-65: character maps to 
2016-09-23 04:55:00 ERROR    SEARCHQUEUE-BACKLOG-307767 :: [Zooqle] :: [cc2875f] Unknown exception while searching Zooqle. Error: u'charmap : title: The Aliens, season: 1, year: 2016, format: HDTV, release_group: 720\xd1\u20ac.|.Sunshine, type: episode, absolute_episode: [], quality: Unknown, episode: [] : error 74 : error 75 : character maps to '
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 212, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 239, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0440' in position 74: character maps to 
2016-09-23 04:54:26 ERROR    SEARCHQUEUE-BACKLOG-299964 :: [Zooqle] :: [cc2875f] Unknown exception while searching Zooqle. Error: u'charmap : title: Occupied, season: 1, year: 2015, format: WEB-DL, release_group: 720\xd1\u20ac.|.50.FPS.|.L1, type: episode, absolute_episode: [], quality: Unknown, episode: [] : error 74 : error 75 : character maps to '
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 212, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 239, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0440' in position 74: character maps to 
2016-09-23 04:38:12 ERROR    SEARCHQUEUE-BACKLOG-80379 :: [Torrentz2] :: [cc2875f] Unknown exception while searching Torrentz2. Error: u'charmap : title: The Big Bang Theory, episode: [2], episode_title: \xd1\ufffd\xd0\xb5\xd0\xb7\xd0\xbe\xd0\xbd, release_group: iPod, type: episode, absolute_episode: [], quality: Unknown, season: None : error 57 : error 62 : character maps to '
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 212, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 239, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 57-61: character maps to 
2016-09-23 04:23:43 ERROR    SHOWQUEUE-REFRESH :: [cc2875f] 71663: Error while refreshing show The Simpsons. Error: 'charmap' codec can't encode character u'\u042f' in position 65: character maps to 
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\show_queue.py", line 566, in run
    self.show.refresh_dir()
  File "C:\SickRageMedusa\**********\tv.py", line 1266, in refresh_dir
    self.load_episodes_from_dir()
  File "C:\SickRageMedusa\**********\tv.py", line 581, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(ek(os.path.join, self.location, media_file))
  File "C:\SickRageMedusa\**********\tv.py", line 817, in make_ep_from_file
    'normal', 'anime')[self.is_anime]).parse(filepath)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 239, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u042f' in position 65: character maps to 
2016-09-23 03:02:38 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [Norbits] :: [cc2875f] Unknown exception while searching Norbits. Error: "local variable 'jdata' referenced before assignment"
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 179, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "C:\SickRageMedusa\**********\providers\torrent\json\norbits.py", line 103, in search
    results += self.parse(jdata, mode)
UnboundLocalError: local variable 'jdata' referenced before assignment
2016-09-23 02:19:04 ERROR    SEARCHQUEUE-BACKLOG-75978 :: [Torrentz2] :: [cc2875f] Unknown exception while searching Torrentz2. Error: u'charmap : title: Family Guy, season: 7, episode_title: Compressed, release_group: By.Tr\xce\u201dnC\xce\u201dt, type: episode, absolute_episode: [], quality: Unknown, episode: [] : error 77 : error 78 : character maps to '
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 212, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 239, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0394' in position 77: character maps to 
2016-09-23 01:37:43 ERROR    SEARCHQUEUE-BACKLOG-73141 :: [Torrentz2] :: [cc2875f] Unknown exception while searching Torrentz2. Error: u'charmap : title: American Dad, episode: [3], episode_title: \xd0\xb9 \xd1\ufffd\xd0\xb5\xd0\xb7\xd0\xbe\xd0\xbd, type: episode, absolute_episode: [], quality: Unknown, season: None : error 50 : error 51 : character maps to '
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 212, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 233, in parse
    result = self._parse_string(name)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 207, in _parse_string
    result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0439' in position 50: character maps to 
2016-09-23 01:26:34 ERROR    SEARCHQUEUE-BACKLOG-73141 :: [Torrentz2] :: [cc2875f] Unknown exception while searching Torrentz2. Error: u'charmap : title: American Dad, episode: [2], episode_title: \xd0\xb9 \xd1\ufffd\xd0\xb5\xd0\xb7\xd0\xbe\xd0\xbd, type: episode, absolute_episode: [], quality: Unknown, season: None : error 50 : error 51 : character maps to '
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\search\core.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "C:\SickRageMedusa\**********\providers\GenericProvider.py", line 212, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 233, in parse
    result = self._parse_string(name)
  File "C:\SickRageMedusa\**********\name_parser\parser.py", line 207, in _parse_string
    result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0439' in position 50: character maps to 
2016-09-23 01:16:16 ERROR    SEARCHQUEUE-BACKLOG-73141 :: [Torrentz2] :: [cc2875f] Unknown exception while searching Torrentz2. Error: u'charmap : title: American Dad, episode: [1], episode_title: \xd0\xb9 \xd1\ufffd\xd0\xb5\xd0\xb7\xd0\xbe\xd0\xbd, type: episode, absolute_episode: [], quality: Unknown, season: None : error 50 : error 51 : character maps to '
Traceback (most recent call last):
```

**Comment by fernandog** [comment]
@wimpyrbx already fixed?
