### ISSUE TITLE
SHOWQUEUE-REFRESH :: [c701877] 248736: Error while refreshing show

### ISSUE THREAD

**Issue by whipcracker** [pymedusa/SickRage#1222]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: c7018776ec3c169d0c17fe220651b1243bc84ea5
OS: Windows 10 Pro 64 bit
What you did: Zilch
What happened: This error msg appeared. Only getting the error with Grimm and Person of Interest. This issue has popped up before, but I've paid no real attention to it.
What you expected: Honestly, no idea..
Logs:
```
2016-10-04 14:37:29 ERROR    SHOWQUEUE-REFRESH :: [c701877] 248736: Error while refreshing show Grimm. Error: 'charmap' codec can't encode character u'\u0301' in position 59: character maps to 
Traceback (most recent call last):
  File "C:\Medusa\sickbeard\show_queue.py", line 565, in run
    self.show.refresh_dir()
  File "C:\Medusa\sickbeard\tv.py", line 1267, in refresh_dir
    self.load_episodes_from_dir()
  File "C:\Medusa\sickbeard\tv.py", line 582, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(ek(os.path.join, self.location, media_file))
  File "C:\Medusa\sickbeard\tv.py", line 818, in make_ep_from_file
    'normal', 'anime')[self.is_anime]).parse(filepath)
  File "C:\Medusa\sickbeard\name_parser\parser.py", line 240, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u0301' in position 59: character maps to 
2016-10-04 14:34:09 ERROR    SHOWQUEUE-REFRESH :: [c701877] 248742: Error while refreshing show Person of Interest. Error: 'charmap' codec can't encode character u'\u03c0' in position 69: character maps to 
Traceback (most recent call last):
  File "C:\Medusa\sickbeard\show_queue.py", line 565, in run
    self.show.refresh_dir()
  File "C:\Medusa\sickbeard\tv.py", line 1267, in refresh_dir
    self.load_episodes_from_dir()
  File "C:\Medusa\sickbeard\tv.py", line 582, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(ek(os.path.join, self.location, media_file))
  File "C:\Medusa\sickbeard\tv.py", line 818, in make_ep_from_file
    'normal', 'anime')[self.is_anime]).parse(filepath)
  File "C:\Medusa\sickbeard\name_parser\parser.py", line 240, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result))
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u03c0' in position 69: character maps to 
```

**Comment by fernandog** [comment]
@medariox i thought we removed the `str()` in `logger.debug('Parsed {name} into {result}', name=name, result=str(result))`

**Comment by ratoaq2** [comment]
This is fixed in develop, not yet released

**Comment by fernandog** [comment]
Its a similar issue that got fixed:
https://github.com/pymedusa/SickRage/issues/1161

**Comment by whipcracker** [comment]
I remember a similar issue before, so good to know it's fixed in Dev :+1: 

Will close and wait for the next update.

Cheers lads!
