### ISSUE TITLE
[APP SUBMITTED]: UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 106: character maps to <undefined>

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/SickRage#1236]
### INFO
**Python Version**: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/SickRage@61b60522b98450f541a0f9c4b57c8242338432ba
**Link to Log**: https://gist.github.com/5961cc0783a7d558b4e72c8edf209972
### ERROR
<pre>
2016-10-09 07:42:10 ERROR    Thread-18 :: [61b6052] Failed doing web ui callback: Traceback (most recent call last):
  File "C:\pymedusaSickRage\medusa\server\web\core\base.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\pymedusaSickRage\medusa\server\web\core\error_logs.py", line 133, in viewlog
    predicate=lambda l: filter_logline(l, min_level=min_level,
  File "C:\pymedusaSickRage\medusa\logger.py", line 142, in read_loglines
    logline = LogLine.from_line(line)
  File "C:\pymedusaSickRage\medusa\logger.py", line 375, in from_line
    lines = line.split('\n')
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 106: character maps to <undefined>
Traceback (most recent call last):
  File "C:\pymedusaSickRage\medusa\server\web\core\base.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\pymedusaSickRage\medusa\server\web\core\error_logs.py", line 133, in viewlog
    predicate=lambda l: filter_logline(l, min_level=min_level,
  File "C:\pymedusaSickRage\medusa\logger.py", line 142, in read_loglines
    logline = LogLine.from_line(line)
  File "C:\pymedusaSickRage\medusa\logger.py", line 375, in from_line
    lines = line.split('\n')
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 106: character maps to <undefined>
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ratoaq2** [comment]
[This](https://github.com/pymedusa/SickRage/pull/1237) fixes your issue.

Thanks for reporting it.
A fix will reach develop soon

**Comment by whipcracker** [comment]
### INFO
**Python Version**: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.2`
**Commit**: pymedusa/SickRage@47eb02f16dbf48192db764a080d38c68bd5ec0c9
**Link to Log**: https://gist.github.com/e5c05b7c7a26d76209bf1ea678cce160
### ERROR
<pre>
2016-10-24 16:26:15 ERROR    Thread-30 :: [47eb02f] Failed doing web ui callback: Traceback (most recent call last):
  File "C:\Medusa\medusa\server\web\core\base.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\Medusa\medusa\server\web\core\error_logs.py", line 133, in viewlog
    predicate=lambda l: filter_logline(l, min_level=min_level,
  File "C:\Medusa\medusa\logger.py", line 142, in read_loglines
    logline = LogLine.from_line(line)
  File "C:\Medusa\medusa\logger.py", line 375, in from_line
    lines = line.split('\n')
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 114: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Medusa\medusa\server\web\core\base.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\Medusa\medusa\server\web\core\error_logs.py", line 133, in viewlog
    predicate=lambda l: filter_logline(l, min_level=min_level,
  File "C:\Medusa\medusa\logger.py", line 142, in read_loglines
    logline = LogLine.from_line(line)
  File "C:\Medusa\medusa\logger.py", line 375, in from_line
    lines = line.split('\n')
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 114: character maps to <undefined>
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by whipcracker** [comment]
### INFO
**Python Version**: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.2`
**Commit**: pymedusa/SickRage@47eb02f16dbf48192db764a080d38c68bd5ec0c9
**Link to Log**: https://gist.github.com/5580fed73cf12ea6861b1b2a8d6c455e
### ERROR
<pre>
2016-10-24 16:34:34 ERROR    Thread-29 :: [47eb02f] Failed doing web ui callback: Traceback (most recent call last):
  File "C:\Medusa\medusa\server\web\core\base.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\Medusa\medusa\server\web\core\error_logs.py", line 133, in viewlog
    predicate=lambda l: filter_logline(l, min_level=min_level,
  File "C:\Medusa\medusa\logger.py", line 142, in read_loglines
    logline = LogLine.from_line(line)
  File "C:\Medusa\medusa\logger.py", line 375, in from_line
    lines = line.split('\n')
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 114: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Medusa\medusa\server\web\core\base.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\Medusa\medusa\server\web\core\error_logs.py", line 133, in viewlog
    predicate=lambda l: filter_logline(l, min_level=min_level,
  File "C:\Medusa\medusa\logger.py", line 142, in read_loglines
    logline = LogLine.from_line(line)
  File "C:\Medusa\medusa\logger.py", line 375, in from_line
    lines = line.split('\n')
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 114: character maps to <undefined>
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
