### ISSUE TITLE
[APP SUBMITTED]: zip argument #1 must support iteration

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#264]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-3-osmc-armv7l-with-debian-8.4**
Locale: UTF-8
Branch: **fix_concurrence**
Commit: PyMedusa/SickRage@70dc4a81047b35d82a4f1e312ca0174269cdef8b
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [80123f9] Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 322, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 1485, in manualSearchCheckCache
    episodesInSearch = collectEpisodesFromSearchThread(show)
  File "/home/osmc/SickRage/sickbeard/manual_search.py", line 148, in collectEpisodesFromSearchThread
    if not [i for i, j in zip(search_thread.segment, episodes) if i.indexerid == j['episodeindexid']]:
TypeError: zip argument #1 must support iteration

```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-3-osmc-armv7l-with-debian-8.4**
Locale: UTF-8
Branch: **fix_concurrence**
Commit: PyMedusa/SickRage@70dc4a81047b35d82a4f1e312ca0174269cdef8b
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [80123f9] Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 322, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 1485, in manualSearchCheckCache
    episodesInSearch = collectEpisodesFromSearchThread(show)
  File "/home/osmc/SickRage/sickbeard/manual_search.py", line 148, in collectEpisodesFromSearchThread
    if not [i for i, j in zip(search_thread.segment, episodes) if i.indexerid == j['episodeindexid']]:
TypeError: zip argument #1 must support iteration

```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-3-osmc-armv7l-with-debian-8.4**
Locale: UTF-8
Branch: **fix_concurrence**
Commit: PyMedusa/SickRage@70dc4a81047b35d82a4f1e312ca0174269cdef8b
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [80123f9] Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 322, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 1485, in manualSearchCheckCache
    episodesInSearch = collectEpisodesFromSearchThread(show)
  File "/home/osmc/SickRage/sickbeard/manual_search.py", line 148, in collectEpisodesFromSearchThread
    if not [i for i, j in zip(search_thread.segment, episodes) if i.indexerid == j['episodeindexid']]:
TypeError: zip argument #1 must support iteration

```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-3-osmc-armv7l-with-debian-8.4**
Locale: UTF-8
Branch: **fix_concurrence**
Commit: PyMedusa/SickRage@70dc4a81047b35d82a4f1e312ca0174269cdef8b
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [80123f9] Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 322, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 1485, in manualSearchCheckCache
    episodesInSearch = collectEpisodesFromSearchThread(show)
  File "/home/osmc/SickRage/sickbeard/manual_search.py", line 148, in collectEpisodesFromSearchThread
    if not [i for i, j in zip(search_thread.segment, episodes) if i.indexerid == j['episodeindexid']]:
TypeError: zip argument #1 must support iteration

```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@p0psicles not sure why this is happening
