### ISSUE TITLE
TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by medariox** [pymedusa/SickRage#274]
```
2016-04-05 12:05:53 FINDSUBTITLES :: [a90e41d] Traceback (most recent call last):
  File "/home/dariox/.sickrage/sickbeard/subtitles.py", line 325, in download_best_subs
    get_subtitle_description(subtitle)), logger.DEBUG)
  File "/home/dariox/.sickrage/sickbeard/subtitles.py", line 489, in get_subtitle_description
    return subtitle.id + '-' + desc if desc not in subtitle.id else desc
TypeError: argument of type 'int' is not iterable
```
@ratoaq2 
Caused by Itasa subtitles provider on download.

**Comment by ratoaq2** [comment]
Ok. I'll fix that later today.

**Comment by ratoaq2** [comment]
This should be fixed as soon as [PR 270](https://github.com/pymedusa/SickRage/pull/270) is merged.

**Comment by ratoaq2** [comment]
It's on develop branch. It should be fixed. Otherwise reopen the bug.
