### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#288]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-3-osmc-armv7l-with-debian-8.4**
Locale: UTF-8
Branch: **logging_improvements**
Commit: PyMedusa/SickRage@9ea0d8f6b6836f345a1e76b6a9f35aed53b64861
No Log available with ERRORS:
### ERROR
```
19:33:06 INFO::FINDSUBTITLES :: [9ea0d8f] Scanning video "Marvel's.Agents.of.S.H.I.E.L.D.S03E15.Spacetime.1080p.WEB-DL.DD5.1.H.264-MAoS.mkv" in '/media/SAMSUNG/media/downloaded/series/Marvels.Agents.of.S.H.I.E.L.D.S03E15.Spacetime.1080p.WEB-DL.DD5.1.H264-MAoS[rarbg]'
19:33:12 ERROR::FINDSUBTITLES :: [9ea0d8f] Failed to refine video
Traceback (most recent call last):
  File "/home/osmc/SickRage/lib/subliminal/core.py", line 543, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "/home/osmc/SickRage/lib/subliminal/refiners/tvdb.py", line 274, in refine
    results = search_series(video.series.lower())
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1053, in decorate
    should_cache_fn)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 657, in get_or_create
    async_creator) as value:
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 625, in gen_value
    created_value = creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1049, in creator
    return fn(*arg, **kw)
  File "/home/osmc/SickRage/lib/subliminal/refiners/tvdb.py", line 213, in search_series
    return sorted(tvdb_client.search_series(name), key=match)
TypeError: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
Also:

```
AATypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
AA    release_path = os.path.join(dirpath, release_name + fileext)
AA  File "/home/osmc/SickRage/sickbeard/refiners/release.py", line 50, in refine
AA    refiner_manager[refiner].plugin(video, **kwargs)
AA  File "/home/osmc/SickRage/lib/subliminal/core.py", line 543, in refine
AATraceback (most recent call last):
2016-04-06 19:34:14 ERROR    FINDSUBTITLES :: [9ea0d8f] Failed to refine video
```

**Comment by fernandog** [comment]
https://github.com/Diaoul/subliminal/issues/601

**Comment by fernandog** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-3-osmc-armv7l-with-debian-8.4**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@1f87e70265a8101fb9501e499a9ab15ba0da6603
No Log available with ERRORS:
### ERROR
```
08:24:16 ERROR::FINDSUBTITLES :: [1f87e70] Failed to refine video
Traceback (most recent call last):
  File "/home/osmc/SickRage/lib/subliminal/core.py", line 543, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "/home/osmc/SickRage/lib/subliminal/refiners/tvdb.py", line 274, in refine
    results = search_series(video.series.lower())
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1053, in decorate
    should_cache_fn)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 657, in get_or_create
    async_creator) as value:
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 625, in gen_value
    created_value = creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1049, in creator
    return fn(*arg, **kw)
  File "/home/osmc/SickRage/lib/subliminal/refiners/tvdb.py", line 213, in search_series
    return sorted(tvdb_client.search_series(name), key=match)
TypeError: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@0f7b155d748fead090706f6d22c529b9a5736740
No Log available with ERRORS:
### ERROR
```
FINDSUBTITLES :: [0f7b155] Unable to find subtitles for Archer (2009) S03E12. Error: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 844, in run
    episode_object.download_subtitles()
  File "/home/home/SickRage/sickbeard/tv.py", line 1424, in download_subtitles
    status=self.status, existing_subtitles=self.subtitles)
  File "/home/home/SickRage/sickbeard/subtitles.py", line 252, in download_subtitles
    languages = get_needed_languages(existing_subtitles)
  File "/home/home/SickRage/sickbeard/subtitles.py", line 135, in get_needed_languages
    return {from_code(language) for language in wanted_languages().difference(subtitles)}
TypeError: 'NoneType' object is not iterable
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@duramato  your wanted subtitle is empty. check config file to confirm wanted is empty.
