### ISSUE TITLE
[APP SUBMITTED]: ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#297]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-3-osmc-armv7l-with-debian-8.4**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@89a459923cfb2020bc32aab80527bc8a263731d5
No Log available with ERRORS:
### ERROR
```
13:02:19 ERROR::FINDSUBTITLES :: [89a4599] Unexpected error in provider 'legendastv'
Traceback (most recent call last):
  File "/home/osmc/SickRage/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/home/osmc/SickRage/lib/subliminal/providers/legendastv.py", line 413, in list_subtitles
    return [s for l in languages for s in self.query(l, title, season=season, episode=episode, year=video.year)]
  File "/home/osmc/SickRage/lib/subliminal/providers/legendastv.py", line 316, in query
    titles = self.search_titles(sanitize(title))
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1053, in decorate
    should_cache_fn)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 657, in get_or_create
    async_creator) as value:
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 625, in gen_value
    created_value = creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1049, in creator
    return fn(*arg, **kw)
  File "/home/osmc/SickRage/lib/subliminal/providers/legendastv.py", line 205, in search_titles
    r = self.session.get(self.server_url + 'legenda/sugestao/{}'.format(title), timeout=10)
  File "/home/osmc/SickRage/lib/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/home/osmc/SickRage/lib/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/osmc/SickRage/lib/requests/sessions.py", line 578, in send
    r = adapter.send(request, **kwargs)
  File "/home/osmc/SickRage/lib/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2 makes sense? can be a racing condition?

https://github.com/kennethreitz/requests/issues/2364#issuecomment-186214402

**Comment by labrys** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10240**
Locale: cp1252
Branch: **develop**
Commit: PyMedusa/SickRage@1cf76bac0801a4f52614ddf64d435fe50086d239
No Log available with ERRORS:
### ERROR
```
11:44:43 ERROR::FINDSUBTITLES :: [1cf76ba] Unexpected error in provider 'legendastv'
Traceback (most recent call last):
  File "H:\usr\local\sickrage\lib\subliminal\core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "H:\usr\local\sickrage\lib\subliminal\providers\legendastv.py", line 412, in list_subtitles
    return [s for l in languages for s in self.query(l, title, season=season, episode=episode, year=video.year)]
  File "H:\usr\local\sickrage\lib\subliminal\providers\legendastv.py", line 315, in query
    titles = self.search_titles(sanitize(title))
  File "H:\usr\local\sickrage\lib\dogpile\cache\region.py", line 1040, in decorate
    should_cache_fn)
  File "H:\usr\local\sickrage\lib\dogpile\cache\region.py", line 651, in get_or_create
    async_creator) as value:
  File "H:\usr\local\sickrage\lib\dogpile\core\dogpile.py", line 158, in __enter__
    return self._enter()
  File "H:\usr\local\sickrage\lib\dogpile\core\dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "H:\usr\local\sickrage\lib\dogpile\core\dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "H:\usr\local\sickrage\lib\dogpile\cache\region.py", line 619, in gen_value
    created_value = creator()
  File "H:\usr\local\sickrage\lib\dogpile\cache\region.py", line 1036, in creator
    return fn(*arg, **kw)
  File "H:\usr\local\sickrage\lib\subliminal\providers\legendastv.py", line 205, in search_titles
    r = self.session.get(self.server_url + 'legenda/sugestao/{}'.format(title), timeout=10)
  File "H:\usr\local\sickrage\lib\requests\sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "H:\usr\local\sickrage\lib\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "H:\usr\local\sickrage\lib\requests\sessions.py", line 578, in send
    r = adapter.send(request, **kwargs)
  File "H:\usr\local\sickrage\lib\requests\adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2 how to debug this? Can we patch requests to add some sort of log? are you getting this error too?

**Comment by fernandog** [comment]
@ratoaq2 added the raise as we talked

```
2016-04-12 19:12:40 FINDSUBTITLES :: [0e08045] Unexpected error in provider 'legendastv'
Traceback (most recent call last):
  File "/home/osmc/SickRage/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/home/osmc/SickRage/lib/subliminal/providers/legendastv.py", line 440, in list_subtitles
    return [s for l in languages for s in self.query(l, title, season=season, episode=episode, year=video.year)]
  File "/home/osmc/SickRage/lib/subliminal/providers/legendastv.py", line 400, in query
    self.download_archive(a)
  File "/home/osmc/SickRage/lib/subliminal/providers/legendastv.py", line 324, in download_archive
    r = self.session.get(self.server_url + 'downloadarquivo/{}'.format(archive.id))
  File "/home/osmc/SickRage/lib/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/home/osmc/SickRage/lib/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/osmc/SickRage/lib/requests/sessions.py", line 578, in send
    r = adapter.send(request, **kwargs)
  File "/home/osmc/SickRage/lib/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/home/osmc/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/osmc/SickRage/lib/requests/packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/osmc/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/home/osmc/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
ProtocolError: ('Connection aborted.', BadStatusLine("''",))
```
