### ISSUE TITLE
[APP SUBMITTED]: Expecting , delimiter: line 2918 column 5 (char 66143)

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#316]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-3-osmc-armv7l-with-debian-8.4**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@d47493d2dac23359d47da5a3fb781921296bb49f
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [d47493d] Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/scene_exceptions.py", line 201, in retrieve_exceptions
    jdata = helpers.getURL(loc, session=sickbeard.indexerApi(INDEXER_TVDB).session, returns='json')
  File "/home/osmc/SickRage/sickbeard/helpers.py", line 1453, in getURL
    return resp if response_type == u'response' or response_type is None else resp.json() if response_type == u'json' else getattr(resp, response_type, resp)
  File "/home/osmc/SickRage/lib/requests/models.py", line 800, in json
    self.content.decode(encoding), **kwargs
  File "/home/osmc/SickRage/lib/simplejson/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/home/osmc/SickRage/lib/simplejson/decoder.py", line 335, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/osmc/SickRage/lib/simplejson/decoder.py", line 351, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/osmc/SickRage/lib/simplejson/scanner.py", line 36, in _scan_once
    return parse_object((string, idx + 1), encoding, strict, _scan_once, object_hook)
  File "/home/osmc/SickRage/lib/simplejson/decoder.py", line 202, in JSONObject
    raise ValueError(errmsg("Expecting , delimiter", s, end - 1))
ValueError: Expecting , delimiter: line 2918 column 5 (char 66143)
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/scene_exceptions.py", line 201, in retrieve_exceptions
    jdata = helpers.getURL(loc, session=sickbeard.indexerApi(INDEXER_TVDB).session, returns='json')
  File "/home/osmc/SickRage/sickbeard/helpers.py", line 1453, in getURL
    return resp if response_type == u'response' or response_type is None else resp.json() if response_type == u'json' else getattr(resp, response_type, resp)
  File "/home/osmc/SickRage/lib/requests/models.py", line 800, in json
    self.content.decode(encoding), **kwargs
  File "/home/osmc/SickRage/lib/simplejson/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/home/osmc/SickRage/lib/simplejson/decoder.py", line 335, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/osmc/SickRage/lib/simplejson/decoder.py", line 351, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/osmc/SickRage/lib/simplejson/scanner.py", line 36, in _scan_once
    return parse_object((string, idx + 1), encoding, strict, _scan_once, object_hook)
  File "/home/osmc/SickRage/lib/simplejson/decoder.py", line 202, in JSONObject
    raise ValueError(errmsg("Expecting , delimiter", s, end - 1))
ValueError: Expecting , delimiter: line 2918 column 5 (char 66143)
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-3-osmc-armv7l-with-debian-8.4**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@d47493d2dac23359d47da5a3fb781921296bb49f
No Log available with ERRORS:
### ERROR
```
MAIN :: [d47493d] Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/scene_exceptions.py", line 201, in retrieve_exceptions
    jdata = helpers.getURL(loc, session=sickbeard.indexerApi(INDEXER_TVDB).session, returns='json')
  File "/home/osmc/SickRage/sickbeard/helpers.py", line 1453, in getURL
    return resp if response_type == u'response' or response_type is None else resp.json() if response_type == u'json' else getattr(resp, response_type, resp)
  File "/home/osmc/SickRage/lib/requests/models.py", line 800, in json
    self.content.decode(encoding), **kwargs
  File "/home/osmc/SickRage/lib/simplejson/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/home/osmc/SickRage/lib/simplejson/decoder.py", line 335, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/osmc/SickRage/lib/simplejson/decoder.py", line 351, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/osmc/SickRage/lib/simplejson/scanner.py", line 36, in _scan_once
    return parse_object((string, idx + 1), encoding, strict, _scan_once, object_hook)
  File "/home/osmc/SickRage/lib/simplejson/decoder.py", line 202, in JSONObject
    raise ValueError(errmsg("Expecting , delimiter", s, end - 1))
ValueError: Expecting , delimiter: line 2918 column 5 (char 66143)
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/scene_exceptions.py", line 201, in retrieve_exceptions
    jdata = helpers.getURL(loc, session=sickbeard.indexerApi(INDEXER_TVDB).session, returns='json')
  File "/home/osmc/SickRage/sickbeard/helpers.py", line 1453, in getURL
    return resp if response_type == u'response' or response_type is None else resp.json() if response_type == u'json' else getattr(resp, response_type, resp)
  File "/home/osmc/SickRage/lib/requests/models.py", line 800, in json
    self.content.decode(encoding), **kwargs
  File "/home/osmc/SickRage/lib/simplejson/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/home/osmc/SickRage/lib/simplejson/decoder.py", line 335, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/osmc/SickRage/lib/simplejson/decoder.py", line 351, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/osmc/SickRage/lib/simplejson/scanner.py", line 36, in _scan_once
    return parse_object((string, idx + 1), encoding, strict, _scan_once, object_hook)
  File "/home/osmc/SickRage/lib/simplejson/decoder.py", line 202, in JSONObject
    raise ValueError(errmsg("Expecting , delimiter", s, end - 1))
ValueError: Expecting , delimiter: line 2918 column 5 (char 66143)
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
