### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\xea' in position 93: ordinal not in range(128)

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#318]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@d47493d2dac23359d47da5a3fb781921296bb49f
No Log available with ERRORS:
### ERROR
```
FINDSUBTITLES :: [d47493d] Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 338, in download_best_subs
    save_subtitles(video, found_subtitles, directory=subtitles_dir, single=not sickbeard.SUBTITLES_MULTI)
  File "/home/home/SickRage/lib/subliminal/core.py", line 695, in save_subtitles
    with io.open(subtitle_path, 'wb') as f:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 93: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 338, in download_best_subs
    save_subtitles(video, found_subtitles, directory=subtitles_dir, single=not sickbeard.SUBTITLES_MULTI)
  File "/home/home/SickRage/lib/subliminal/core.py", line 695, in save_subtitles
    with io.open(subtitle_path, 'wb') as f:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 93: ordinal not in range(128)
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@duramato new more logs with provider and etc. have subliminal logs enabled?

**Comment by duramato** [comment]
Yes but dont have this part now, they have rolled over.
Why didnt it attach them?

**Comment by fernandog** [comment]
https://github.com/pymedusa/SickRage/commit/784a614f0befef01041356d47c6eeef4b9e40b2d

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@f358c8be1995b6c91d0951809318c3ef212b7bcc
No Log available with ERRORS:
### ERROR
```
FINDSUBTITLES :: [f358c8b] Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 325, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 483, in get_subtitle_description
    sub_id = str(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 118: invalid start byte
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 325, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 483, in get_subtitle_description
    sub_id = str(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 118: invalid start byte
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@f358c8be1995b6c91d0951809318c3ef212b7bcc
No Log available with ERRORS:
### ERROR
```
FINDSUBTITLES :: [f358c8b] Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 325, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 483, in get_subtitle_description
    sub_id = str(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 71: invalid start byte
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 325, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 483, in get_subtitle_description
    sub_id = str(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 71: invalid start byte
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by labrys** [comment]
@duramato Have you had any more issues with this?

**Comment by ratoaq2** [comment]
Reopen if the issue reappears.
