### ISSUE TITLE
[APP SUBMITTED]: 11:44:48 ERROR::FINDSUBTITLES :: [1cf76ba] No show id found for u'Joker Game' ({'year': 2016})
None

### ISSUE THREAD

**Issue by labrys** [pymedusa/SickRage#339]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10240**
Locale: cp1252
Branch: **develop**
Commit: PyMedusa/SickRage@1cf76bac0801a4f52614ddf64d435fe50086d239
No Log available with ERRORS:
### ERROR
```
11:44:48 ERROR::FINDSUBTITLES :: [1cf76ba] No show id found for u'Joker Game' ({'year': 2016})
None
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by labrys** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10240**
Locale: cp1252
Branch: **develop**
Commit: PyMedusa/SickRage@1cf76bac0801a4f52614ddf64d435fe50086d239
No Log available with ERRORS:
### ERROR
```
11:44:48 ERROR::FINDSUBTITLES :: [1cf76ba] Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "H:\usr\local\sickrage\lib\subliminal\core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "H:\usr\local\sickrage\lib\subliminal\providers\addic7ed.py", line 269, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "H:\usr\local\sickrage\lib\subliminal\providers\addic7ed.py", line 234, in query
    raise TooManyRequests()
TooManyRequests
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
