### ISSUE TITLE
[APP SUBMITTED]: 'str' object has no attribute 'show'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#364]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@784a614f0befef01041356d47c6eeef4b9e40b2d
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [Speedcd] :: [784a614] Failed doing webui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 322, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 1544, in snatchSelection
    show_all_results=show_all_results, **search_show)
  File "/home/home/SickRage/sickbeard/manual_search.py", line 218, in get_provider_cache_results
    ep_queue_item = search_queue.ForcedSearchQueueItem(ep_obj.show, ep_obj, bool(int(down_cur_quality)), True)  # pylint: disable=maybe-no-member
AttributeError: 'str' object has no attribute 'show'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 322, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 1544, in snatchSelection
    show_all_results=show_all_results, **search_show)
  File "/home/home/SickRage/sickbeard/manual_search.py", line 218, in get_provider_cache_results
    ep_queue_item = search_queue.ForcedSearchQueueItem(ep_obj.show, ep_obj, bool(int(down_cur_quality)), True)  # pylint: disable=maybe-no-member
AttributeError: 'str' object has no attribute 'show'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
not a clue what happened. need to explain what you did.
@p0psicles

**Comment by duramato** [comment]
Normal manual ep search iir

**Comment by fernandog** [comment]
which show? happens all the time?

**Comment by duramato** [comment]
Happened just this time

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **backlog-force-stop**
Commit: PyMedusa/SickRage@3385229f8a0d54019bda23a955c705f47bfc42e1
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [3385229] Exception generated in thread POSTPROCESSER: 
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/scheduler.py", line 106, in run
    self.action.run(self.force)
  File "/home/home/SickRage/sickbeard/auto_postprocessor.py", line 56, in run
    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)
  File "/home/home/SickRage/sickbeard/processTV.py", line 248, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/home/home/SickRage/sickbeard/processTV.py", line 574, in process_media
    result.result = processor.process()
  File "/home/home/SickRage/sickbeard/postProcessor.py", line 1182, in process
    cur_ep.refreshSubtitles()
  File "/home/home/SickRage/sickbeard/tv.py", line 1411, in refreshSubtitles
    self.saveToDB()
  File "/home/home/SickRage/sickbeard/tv.py", line 1951, in saveToDB
    "subtitles": ",".join(self.subtitles),
TypeError
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@duramato need to open database for that show, check tv_episodes table and check column "subtitles" for that show+episode

**Comment by duramato** [comment]
```
2016-04-12 19:20:37 DEBUG    POSTPROCESSER :: [3385229] 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/scheduler.py", line 106, in run\n    self.action.run(self.force)\n  File "/home/home/SickRage/sickbeard/auto_postprocessor.py", line 56, in run\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)\n  File "/home/home/SickRage/sickbeard/processTV.py", line 248, in processDir\n    process_media(path, [video], nzbName, process_method, force, is_priority, result)\n  File "/home/home/SickRage/sickbeard/processTV.py", line 574, in process_media\n    result.result = processor.process()\n  File "/home/home/SickRage/sickbeard/postProcessor.py", line 1182, in process\n    cur_ep.refreshSubtitles()\n  File "/home/home/SickRage/sickbeard/tv.py", line 1411, in refreshSubtitles\n    self.saveToDB()\n  File "/home/home/SickRage/sickbeard/tv.py", line 1951, in saveToDB\n    "subtitles": ",".join(self.subtitles),\nTypeError\n'
AATypeError
AA    "subtitles": ",".join(self.subtitles),
AA  File "/home/home/SickRage/sickbeard/tv.py", line 1951, in saveToDB
AA    self.saveToDB()
AA  File "/home/home/SickRage/sickbeard/tv.py", line 1411, in refreshSubtitles
AA    cur_ep.refreshSubtitles()
AA  File "/home/home/SickRage/sickbeard/postProcessor.py", line 1182, in process
AA    result.result = processor.process()
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 574, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/home/home/SickRage/sickbeard/processTV.py", line 248, in processDir
AA    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)
AA  File "/home/home/SickRage/sickbeard/auto_postprocessor.py", line 56, in run
AA    self.action.run(self.force)
AA  File "/home/home/SickRage/sickbeard/scheduler.py", line 106, in run
AATraceback (most recent call last):
2016-04-12 19:20:37 ERROR    POSTPROCESSER :: [3385229] Exception generated in thread POSTPROCESSER: 
2016-04-12 19:20:37 DEBUG    POSTPROCESSER :: [3385229] Subtitle changes detected for this show The Tonight Show Starring Jimmy Fallon S03E61. Current subtitles: None
2016-04-12 19:20:37 DEBUG    POSTPROCESSER :: [3385229] Exception caught in subliminal.scan_video, subtitles couldn't be refreshed
2016-04-12 19:20:37 DEBUG    POSTPROCESSER :: [3385229] Exception: Insufficient data to process the guess
2016-04-12 19:20:37 DEBUG    POSTPROCESSER :: [3385229] Scanning video 'The.Tonight.Show.Starring.Jimmy.Fallon.2016.04.11.Ben.Kingsley.Common.Ice.Cube.720p.HDTV.x264-crooks.mkv' in '/media/extssd/Shows/The Tonight Show Starring Jimmy Fallon'
2016-04-12 19:20:37 DEBUG    POSTPROCESSER :: [3385229] Scanning video /media/extssd/Shows/The Tonight Show Starring Jimmy Fallon/The.Tonight.Show.Starring.Jimmy.Fallon.2016.04.11.Ben.Kingsley.Common.Ice.Cube.720p.HDTV.x264-crooks.mkv...
2016-04-12 19:20:37 DEBUG    POSTPROCESSER :: [3385229] Setter sets location to /media/extssd/Shows/The Tonight Show Starring Jimmy Fallon/The.Tonight.Show.Starring.Jimmy.Fallon.2016.04.11.Ben.Kingsley.Common.Ice.Cube.720p.HDTV.x264-crooks.mkv
2016-04-12 19:20:37 DEBUG    POSTPROCESSER :: [3385229] Setting permissions for /media/extssd/Shows/The Tonight Show Starring Jimmy Fallon/The.Tonight.Show.Starring.Jimmy.Fallon.2016.04.11.Ben.Kingsley.Common.Ice.Cube.720p.HDTV.x264-crooks.mkv to 666 as parent directory has 777
2016-04-12 19:20:36 DEBUG    POSTPROCESSER :: [3385229] Hard linking file from /media/extssd/download/shows/jimmy.fallon.2016.04.11.ben.kingsley.720p.hdtv.x264-crooks.mkv to /media/extssd/Shows/The Tonight Show Starring Jimmy Fallon/The.Tonight.Show.Starring.Jimmy.Fallon.2016.04.11.Ben.Kingsley.Common.Ice.Cube.720p.HDTV.x264-crooks.mkv
2016-04-12 19:20:36 DEBUG    POSTPROCESSER :: [3385229] No associated files for /media/extssd/download/shows/jimmy.fallon.2016.04.11.ben.kingsley.720p.hdtv.x264-crooks.mkv were found during this pass
2016-04-12 19:20:36 DEBUG    POSTPROCESSER :: [3385229] Checking if the path /media/extssd/Shows/The Tonight Show Starring Jimmy Fallon already exists
2016-04-12 19:20:36 DEBUG    POSTPROCESSER :: [3385229] Destination folder for this episode: /media/extssd/Shows/The Tonight Show Starring Jimmy Fallon
2016-04-12 19:20:36 DEBUG    POSTPROCESSER :: [3385229] formatting pattern: %S.N.%A.D.%E.N.%RT.%SQ.N-%RG -> The.Tonight.Show.Starring.Jimmy.Fallon.2016.04.11.Ben.Kingsley.Common.Ice.Cube.720p.HDTV.x264-crooks
2016-04-12 19:20:36 DEBUG    POSTPROCESSER :: [3385229] Found codec for 'The Tonight Show Starring Jimmy Fallon: Ben Kingsley, Common, Ice Cube'.
2016-04-12 19:20:36 DEBUG    POSTPROCESSER :: [3385229] Parsed jimmy.fallon.2016.04.11.ben.kingsley.720p.hdtv.x264-crooks into jimmy fallon - 2016-04-11 [GROUP: crooks] [ABD: True] [ANIME: False] [whichReg: ['scene_date_format']]
2016-04-12 19:20:36 DEBUG    POSTPROCESSER :: [3385229] Folder name (shows) appears to be a valid release name. Using it.
2016-04-12 19:20:36 DEBUG    POSTPROCESSER :: [3385229] Found release name jimmy.fallon.2016.04.11.ben.kingsley.720p.hdtv.x264-crooks
2016-04-12 19:20:35 DEBUG    POSTPROCESSER :: [3385229] Trying to determine free space on destination drive
2016-04-12 19:20:35 INFO     POSTPROCESSER :: [3385229] This download is marked a priority download so I'm going to replace an existing file if I find one
2016-04-12 19:20:35 DEBUG    POSTPROCESSER :: [3385229] There is no existing file so there's no worries about replacing it
2016-04-12 19:20:35 DEBUG    POSTPROCESSER :: [3385229] Is ep a priority download: True
2016-04-12 19:20:35 DEBUG    POSTPROCESSER :: [3385229] Medusa snatched this episode and it is not processed before
2016-04-12 19:20:35 DEBUG    POSTPROCESSER :: [3385229] Quality of the episode we're processing: 720p HDTV
2016-04-12 19:20:35 DEBUG    POSTPROCESSER :: [3385229] Snatch history had a quality in it, using that: 720p HDTV
2016-04-12 19:20:35 DEBUG    POSTPROCESSER :: [3385229] Retrieving episode object for 3x61
2016-04-12 19:20:35 DEBUG    POSTPROCESSER :: [3385229] Looks like this is an air-by-date or sports show, attempting to convert the date to season/episode
2016-04-12 19:20:35 DEBUG    POSTPROCESSER :: [3385229] Parsed jimmy.fallon.2016.04.11.ben.kingsley.720p.hdtv.x264-crooks into jimmy fallon - S03E612016-04-11 [GROUP: crooks] [ABD: True] [ANIME: False] [whichReg: ['scene_date_format']]
2016-04-12 19:20:35 DEBUG    POSTPROCESSER :: [3385229] Converted parsed result jimmy.fallon.2016.04.11.ben.kingsley.720p.hdtv.x264-crooks into jimmy fallon - S03E612016-04-11 [GROUP: crooks] [ABD: True] [ANIME: False] [whichReg: ['scene_date_format']]
2016-04-12 19:20:35 DEBUG    POSTPROCESSER :: [3385229] Analyzing name jimmy.fallon.2016.04.11.ben.kingsley.720p.hdtv.x264-crooks.mkv
2016-04-12 19:20:35 INFO     POSTPROCESSER :: [3385229] Processing /media/extssd/download/shows/jimmy.fallon.2016.04.11.ben.kingsley.720p.hdtv.x264-crooks.mkv (None)
```
