### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by labrys** [pymedusa/SickRage#376]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10240**
Locale: cp1252
Branch: **develop**
Commit: PyMedusa/SickRage@1cf76bac0801a4f52614ddf64d435fe50086d239
No Log available with ERRORS:
### ERROR
```
18:32:50 ERROR::POSTPROCESSER :: [1cf76ba] Failed to refine video
Traceback (most recent call last):
  File "H:\usr\local\sickrage\lib\subliminal\core.py", line 543, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "H:\usr\local\sickrage\lib\subliminal\refiners\tvdb.py", line 278, in refine
    results = search_series(video.series.lower())
  File "H:\usr\local\sickrage\lib\dogpile\cache\region.py", line 1040, in decorate
    should_cache_fn)
  File "H:\usr\local\sickrage\lib\dogpile\cache\region.py", line 651, in get_or_create
    async_creator) as value:
  File "H:\usr\local\sickrage\lib\dogpile\core\dogpile.py", line 158, in __enter__
    return self._enter()
  File "H:\usr\local\sickrage\lib\dogpile\core\dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "H:\usr\local\sickrage\lib\dogpile\core\dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "H:\usr\local\sickrage\lib\dogpile\cache\region.py", line 619, in gen_value
    created_value = creator()
  File "H:\usr\local\sickrage\lib\dogpile\cache\region.py", line 1036, in creator
    return fn(*arg, **kw)
  File "H:\usr\local\sickrage\lib\subliminal\refiners\tvdb.py", line 217, in search_series
    return sorted(results, key=match)
  File "H:\usr\local\sickrage\lib\subliminal\refiners\tvdb.py", line 212, in match
    if series['seriesName'].lower() != name and name not in [alias.lower() for alias in series['aliases']]:
AttributeError: 'NoneType' object has no attribute 'lower'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by labrys** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10240**
Locale: cp1252
Branch: **develop**
Commit: PyMedusa/SickRage@1cf76bac0801a4f52614ddf64d435fe50086d239
No Log available with ERRORS:
### ERROR
```
18:32:48 ERROR::POSTPROCESSER :: [1cf76ba] Failed to refine video
Traceback (most recent call last):
  File "H:\usr\local\sickrage\lib\subliminal\core.py", line 543, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "H:\usr\local\sickrage\lib\subliminal\refiners\tvdb.py", line 278, in refine
    results = search_series(video.series.lower())
  File "H:\usr\local\sickrage\lib\dogpile\cache\region.py", line 1040, in decorate
    should_cache_fn)
  File "H:\usr\local\sickrage\lib\dogpile\cache\region.py", line 651, in get_or_create
    async_creator) as value:
  File "H:\usr\local\sickrage\lib\dogpile\core\dogpile.py", line 158, in __enter__
    return self._enter()
  File "H:\usr\local\sickrage\lib\dogpile\core\dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "H:\usr\local\sickrage\lib\dogpile\core\dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "H:\usr\local\sickrage\lib\dogpile\cache\region.py", line 619, in gen_value
    created_value = creator()
  File "H:\usr\local\sickrage\lib\dogpile\cache\region.py", line 1036, in creator
    return fn(*arg, **kw)
  File "H:\usr\local\sickrage\lib\subliminal\refiners\tvdb.py", line 217, in search_series
    return sorted(results, key=match)
  File "H:\usr\local\sickrage\lib\subliminal\refiners\tvdb.py", line 212, in match
    if series['seriesName'].lower() != name and name not in [alias.lower() for alias in series['aliases']]:
AttributeError: 'NoneType' object has no attribute 'lower'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2

**Comment by labrys** [comment]
Related to #375 & #374.  Series Name should be "The A Team" but "Team" is being stripped.

**Comment by fernandog** [comment]
@labrys can you reproduce the issue again with "subliminal logs" enabled please?

**Comment by fernandog** [comment]
@labrys seems that codes doesnt exist anymore in lastes develop. can you confirm it was fixed?
