### ISSUE TITLE
[APP SUBMITTED]: level must be an integer

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#382]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@316d27cc00f0cef7f4dd0840e9c5881bf4a00eaa
No Log available with ERRORS:
### ERROR
```
FINDSUBTITLES :: [316d27c] Exception generated in thread FINDSUBTITLES: level must be an integer
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/scheduler.py", line 106, in run
    self.action.run(self.force)
  File "/home/home/SickRage/sickbeard/subtitles.py", line 804, in run
    logger.log(u'Episode already has all needed subtitles, skipping %s %s', ep_to_sub['show_name'], ep_num)
  File "/usr/lib/python2.7/logging/__init__.py", line 1212, in log
    raise TypeError("level must be an integer")
TypeError: level must be an integer
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2

**Comment by ratoaq2** [comment]
Can someone do a quick fix for that?

`logger.log(u'Episode already has all needed subtitles, skipping %s %s', ep_to_sub['show_name'], ep_num)`

should be

`logger.debug(u'Episode already has all needed subtitles, skipping %s %s', ep_to_sub['show_name'], ep_num)`

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **dedicated-manual-snatch-scheduler**
Commit: PyMedusa/SickRage@2793d9bc3a2ebe018ddcf4d3324b9e0aface945a
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [2793d9b] Exception generated in thread POSTPROCESSER: 
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/scheduler.py", line 106, in run
    self.action.run(self.force)
  File "/home/home/SickRage/sickbeard/auto_postprocessor.py", line 56, in run
    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR, force=force)
  File "/home/home/SickRage/sickbeard/processTV.py", line 286, in processDir
    process_media(processPath, videoInRar, nzbName, u'move', force, is_priority, result)
  File "/home/home/SickRage/sickbeard/processTV.py", line 574, in process_media
    result.result = processor.process()
  File "/home/home/SickRage/sickbeard/postProcessor.py", line 1182, in process
    cur_ep.refreshSubtitles()
  File "/home/home/SickRage/sickbeard/tv.py", line 1411, in refreshSubtitles
    self.saveToDB()
  File "/home/home/SickRage/sickbeard/tv.py", line 1951, in saveToDB
    "subtitles": ",".join(self.subtitles),
TypeError
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2 no idea why reporting this issue ^^ with error "TypeError" here when first issue title error is "level must be an integer"
