### ISSUE TITLE
[APP SUBMITTED]: Invalid control line: '>' in file '/home/osmc/SickRage/gui/slick/views/schedule.mako' at line: 9 char: 1

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#387]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-4-osmc-armv7l-with-debian-8.4**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@a04149d83778e8a22722c79c30d1c18fe819bf59
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [a04149d] Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 322, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 565, in schedule
    t = PageTemplate(rh=self, filename='schedule.mako')
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 140, in __init__
    self.template = lookup.get_template(filename)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/osmc/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/osmc/SickRage/lib/mako/template.py", line 692, in _compile_module_file
    generate_magic_comment=True)
  File "/home/osmc/SickRage/lib/mako/template.py", line 657, in _compile
    node = lexer.parse()
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 237, in parse
    if self.match_control_line():
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 414, in match_control_line
    **self.exception_kwargs)
SyntaxException: Invalid control line: '>' in file '/home/osmc/SickRage/gui/slick/views/schedule.mako' at line: 9 char: 1
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 322, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 565, in schedule
    t = PageTemplate(rh=self, filename='schedule.mako')
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 140, in __init__
    self.template = lookup.get_template(filename)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/osmc/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/osmc/SickRage/lib/mako/template.py", line 692, in _compile_module_file
    generate_magic_comment=True)
  File "/home/osmc/SickRage/lib/mako/template.py", line 657, in _compile
    node = lexer.parse()
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 237, in parse
    if self.match_control_line():
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 414, in match_control_line
    **self.exception_kwargs)
SyntaxException: Invalid control line: '>' in file '/home/osmc/SickRage/gui/slick/views/schedule.mako' at line: 9 char: 1
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-4-osmc-armv7l-with-debian-8.4**
Locale: UTF-8
Branch: **fix_307**
Commit: PyMedusa/SickRage@5b32cfd49d5f931d41162bc3164c25689106c121
Link to Log: https://gist.github.com/c22249f860d924effa0f153daf96c540
### ERROR
```
Thread-13 :: [5b32cfd] Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 322, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 565, in schedule
    t = PageTemplate(rh=self, filename='schedule.mako')
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 140, in __init__
    self.template = lookup.get_template(filename)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/osmc/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/osmc/SickRage/lib/mako/template.py", line 692, in _compile_module_file
    generate_magic_comment=True)
  File "/home/osmc/SickRage/lib/mako/template.py", line 657, in _compile
    node = lexer.parse()
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 237, in parse
    if self.match_control_line():
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 414, in match_control_line
    **self.exception_kwargs)
SyntaxException: Invalid control line: '>' in file '/home/osmc/SickRage/gui/slick/views/schedule.mako' at line: 9 char: 1
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 322, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 565, in schedule
    t = PageTemplate(rh=self, filename='schedule.mako')
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 140, in __init__
    self.template = lookup.get_template(filename)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/osmc/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/osmc/SickRage/lib/mako/template.py", line 692, in _compile_module_file
    generate_magic_comment=True)
  File "/home/osmc/SickRage/lib/mako/template.py", line 657, in _compile
    node = lexer.parse()
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 237, in parse
    if self.match_control_line():
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 414, in match_control_line
    **self.exception_kwargs)
SyntaxException: Invalid control line: '>' in file '/home/osmc/SickRage/gui/slick/views/schedule.mako' at line: 9 char: 1
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
