### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'string'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#394]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **season**
Commit: PyMedusa/SickRage@75db5cd3e636e8832404bb25c005f2849ed15ccb
Link to Log: https://gist.github.com/5853662a22c49aff61029267d0fb5f50
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TransmitTheNet] :: [75db5cd] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/transmitthenet.py", line 152, in search
    title = torrent_row.find('a', onmouseout='return nd();').string
AttributeError: 'NoneType' object has no attribute 'string'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/transmitthenet.py", line 152, in search
    title = torrent_row.find('a', onmouseout='return nd();').string
AttributeError: 'NoneType' object has no attribute 'string'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **season**
Commit: PyMedusa/SickRage@75db5cd3e636e8832404bb25c005f2849ed15ccb
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-284487 :: [TransmitTheNet] :: [75db5cd] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/transmitthenet.py", line 152, in search
    title = torrent_row.find('a', onmouseout='return nd();').string
AttributeError: 'NoneType' object has no attribute 'string'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/transmitthenet.py", line 152, in search
    title = torrent_row.find('a', onmouseout='return nd();').string
AttributeError: 'NoneType' object has no attribute 'string'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **season**
Commit: PyMedusa/SickRage@75db5cd3e636e8832404bb25c005f2849ed15ccb
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295696 :: [TransmitTheNet] :: [75db5cd] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/transmitthenet.py", line 152, in search
    title = torrent_row.find('a', onmouseout='return nd();').string
AttributeError: 'NoneType' object has no attribute 'string'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/transmitthenet.py", line 152, in search
    title = torrent_row.find('a', onmouseout='return nd();').string
AttributeError: 'NoneType' object has no attribute 'string'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **season**
Commit: PyMedusa/SickRage@75db5cd3e636e8832404bb25c005f2849ed15ccb
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-305378 :: [TransmitTheNet] :: [75db5cd] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/transmitthenet.py", line 152, in search
    title = torrent_row.find('a', onmouseout='return nd();').string
AttributeError: 'NoneType' object has no attribute 'string'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/transmitthenet.py", line 152, in search
    title = torrent_row.find('a', onmouseout='return nd();').string
AttributeError: 'NoneType' object has no attribute 'string'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **season**
Commit: PyMedusa/SickRage@75db5cd3e636e8832404bb25c005f2849ed15ccb
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-152831 :: [TransmitTheNet] :: [75db5cd] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/transmitthenet.py", line 152, in search
    title = torrent_row.find('a', onmouseout='return nd();').string
AttributeError: 'NoneType' object has no attribute 'string'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/transmitthenet.py", line 152, in search
    title = torrent_row.find('a', onmouseout='return nd();').string
AttributeError: 'NoneType' object has no attribute 'string'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
