### ISSUE TITLE
[APP SUBMITTED]: multiple repeat

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#409]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@2e2711359d05baca0a0a550bd9345177c7725b05
Link to Log: https://gist.github.com/29f2805b14fc3c767b34030b24ede738
### ERROR
```
Thread-14 :: [2e27113] Unable to get error title : multiple repeat
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/logger.py", line 388, in submit_errors
    title_error = re.match(r'^(.*)(\[[\w]{7}\])\s*+(.*)$', ss(cur_error.message)).group(2)
  File "/usr/lib/python2.7/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python2.7/re.py", line 244, in _compile
    raise error, v # invalid expression
error: multiple repeat
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@2e2711359d05baca0a0a550bd9345177c7725b05
Link to Log: https://gist.github.com/4abe6cb678ecd992c84871e508ebf050
### ERROR
```
Thread-14 :: [2e27113] Unable to get error title : multiple repeat
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/logger.py", line 388, in submit_errors
    title_error = re.match(r'^(.*)(\[[\w]{7}\])\s*+(.*)$', ss(cur_error.message)).group(2)
  File "/usr/lib/python2.7/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python2.7/re.py", line 244, in _compile
    raise error, v # invalid expression
error: multiple repeat
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@2e2711359d05baca0a0a550bd9345177c7725b05
Link to Log: https://gist.github.com/14a10203391525476b4724ae99c6175c
### ERROR
```
Thread-14 :: [2e27113] Unable to get error title : multiple repeat
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/logger.py", line 388, in submit_errors
    title_error = re.match(r'^(.*)(\[[\w]{7}\])\s*+(.*)$', ss(cur_error.message)).group(2)
  File "/usr/lib/python2.7/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python2.7/re.py", line 244, in _compile
    raise error, v # invalid expression
error: multiple repeat
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
```
2016-04-18 00:24:04 Thread-14 :: [2e27113] Unable to get error title : multiple repeat
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/logger.py", line 388, in submit_errors
    title_error = re.match(r'^(.*)(\[[\w]{7}\])\s*+(.*)$', ss(cur_error.message)).group(2)
  File "/usr/lib/python2.7/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python2.7/re.py", line 244, in _compile
    raise error, v # invalid expression
error: multiple repeat
2016-04-18 00:08:34 POSTPROCESSER :: [2e27113] Failed Unrar archive the.characters.s01e05.webrip.x264-fleet.rar: File Open Error, check the parent folder and destination file permissions.
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/processTV.py", line 464, in unRAR
    for x in rar_handle.infolist():
  File "/home/home/SickRage/lib/unrar2/__init__.py", line 125, in infolist
    return list(self.infoiter())
  File "/home/home/SickRage/lib/unrar2/__init__.py", line 120, in infoiter
    for params in RarFileImplementation.infoiter(self):
  File "/home/home/SickRage/lib/unrar2/unix.py", line 130, in infoiter
    raise FileOpenError
FileOpenError
```

**Comment by fernandog** [comment]
@labrys regex works: https://regex101.com/r/aK4gI5/1 so why this error?
