### ISSUE TITLE
Unknown exception while searching LimeTorrents. Error: 'list index out of range'

### ISSUE THREAD

**Issue by medariox** [pymedusa/SickRage#473]
```
2016-04-25 16:04:34 SEARCHQUEUE-MANUAL-304490 :: [LimeTorrents] :: [d0c5e9c] Unknown exception while searching LimeTorrents. Error: 'list index out of range'
Traceback (most recent call last):
  File "/home/orangepi/.sickrage/sickbeard/search.py", line 548, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/orangepi/.sickrage/sickrage/providers/GenericProvider.py", line 149, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/orangepi/.sickrage/sickbeard/providers/limetorrents.py", line 80, in search
    torrent_table = html('table', class_='table2')[0 if mode == 'RSS' else 1]
IndexError: list index out of range
```
@duramato

**Comment by fernandog** [comment]
glad i added the traceback otherwise it will silent fail!

**Comment by duramato** [comment]
RSS or search?

**Comment by fernandog** [comment]
@duramato SEARCHQUEUE-MANUAL-304490 = manual search

**Comment by duramato** [comment]
Manual search updates RSS

**Comment by medariox** [comment]
Manual search. It happens if no result is found.

**Comment by medariox** [comment]
Fixed here https://github.com/pymedusa/SickRage/pull/477
