### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 24025: ordinal not in range(128)

### ISSUE THREAD

**Issue by medariox** [pymedusa/SickRage#484]
```
2016-04-26 14:24:59 Thread-20 :: [6ac2d37] Failed doing webui callback: Traceback (most recent call last):
  File "/home/orangepi/.sickrage/sickbeard/webserve.py", line 322, in async_call
    result = function(**kwargs)
  File "/home/orangepi/.sickrage/sickbeard/webserve.py", line 5090, in saveProviders
    sickbeard.save_config()
  File "/home/orangepi/.sickrage/sickbeard/__init__.py", line 2240, in save_config
    new_config.write()
  File "/home/orangepi/.sickrage/lib/configobj/configobj.py", line 2119, in write
    'ascii')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 24025: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/orangepi/.sickrage/sickbeard/webserve.py", line 322, in async_call
    result = function(**kwargs)
  File "/home/orangepi/.sickrage/sickbeard/webserve.py", line 5090, in saveProviders
    sickbeard.save_config()
  File "/home/orangepi/.sickrage/sickbeard/__init__.py", line 2240, in save_config
    new_config.write()
  File "/home/orangepi/.sickrage/lib/configobj/configobj.py", line 2119, in write
    'ascii')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 24025: ordinal not in range(128)
```

Happens when saving providers.
@labrys 
Caused by configobj update maybe?

**Comment by labrys** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10240**
Locale: cp1252
Branch: **proper-guessit**
Commit: PyMedusa/SickRage@7bed973fd027a071c3c6b4293ecb1ee1902e5906
Link to Log: https://gist.github.com/fe0de2b12434a378a3d2e1500ddbfb60
### ERROR
```
Thread-29 :: [12ab438] Failed doing webui callback: Traceback (most recent call last):
  File "H:\usr\local\sickrage\sickbeard\webserve.py", line 322, in async_call
    result = function(**kwargs)
  File "H:\usr\local\sickrage\sickbeard\webserve.py", line 681, in get_messages
    return json.dumps(messages)
  File "C:\Python27x64\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27x64\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27x64\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 61: invalid continuation byte
Traceback (most recent call last):
  File "H:\usr\local\sickrage\sickbeard\webserve.py", line 322, in async_call
    result = function(**kwargs)
  File "H:\usr\local\sickrage\sickbeard\webserve.py", line 681, in get_messages
    return json.dumps(messages)
  File "C:\Python27x64\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27x64\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27x64\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 61: invalid continuation byte
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **pubdate2**
Commit: PyMedusa/SickRage@5cb34b45906f4e0c51ae5b387517d099cd239e88
No Log available with ERRORS:
### ERROR
```
FINDSUBTITLES :: [512a8a0] Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 326, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 509, in get_subtitle_description
    sub_id = unicode(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 66: invalid start byte
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 326, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 509, in get_subtitle_description
    sub_id = unicode(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 66: invalid start byte
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **pubdate2**
Commit: PyMedusa/SickRage@5cb34b45906f4e0c51ae5b387517d099cd239e88
No Log available with ERRORS:
### ERROR
```
FINDSUBTITLES :: [512a8a0] Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 326, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 509, in get_subtitle_description
    sub_id = unicode(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 117: invalid start byte
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 326, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 509, in get_subtitle_description
    sub_id = unicode(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 117: invalid start byte
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **pubdate2**
Commit: PyMedusa/SickRage@5cb34b45906f4e0c51ae5b387517d099cd239e88
No Log available with ERRORS:
### ERROR
```
FINDSUBTITLES :: [512a8a0] Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 326, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 509, in get_subtitle_description
    sub_id = unicode(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 69: invalid start byte
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 326, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 509, in get_subtitle_description
    sub_id = unicode(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 69: invalid start byte
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **pubdate2**
Commit: PyMedusa/SickRage@5cb34b45906f4e0c51ae5b387517d099cd239e88
No Log available with ERRORS:
### ERROR
```
FINDSUBTITLES :: [512a8a0] Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 326, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 509, in get_subtitle_description
    sub_id = unicode(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 118: invalid start byte
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 326, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 509, in get_subtitle_description
    sub_id = unicode(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 118: invalid start byte
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **pubdate2**
Commit: PyMedusa/SickRage@5cb34b45906f4e0c51ae5b387517d099cd239e88
No Log available with ERRORS:
### ERROR
```
FINDSUBTITLES :: [512a8a0] Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 326, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 509, in get_subtitle_description
    sub_id = unicode(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 63: invalid start byte
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 326, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 509, in get_subtitle_description
    sub_id = unicode(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 63: invalid start byte
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **pubdate2**
Commit: PyMedusa/SickRage@5cb34b45906f4e0c51ae5b387517d099cd239e88
No Log available with ERRORS:
### ERROR
```
FINDSUBTITLES :: [512a8a0] Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 326, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 509, in get_subtitle_description
    sub_id = unicode(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 71: invalid start byte
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/subtitles.py", line 326, in download_best_subs
    subtitle.provider_name, subtitle.language, score, min_score, get_subtitle_description(subtitle)))
  File "/home/home/SickRage/sickbeard/subtitles.py", line 509, in get_subtitle_description
    sub_id = unicode(subtitle.id)
  File "/home/home/SickRage/lib/subliminal/providers/legendastv.py", line 113, in id
    return '%s-%s' % (self.archive.id, self.name.lower())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 71: invalid start byte
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ratoaq2** [comment]
Fixed with https://github.com/pymedusa/SickRage/commit/a6c9c37e2729b9db83a5c70cf4978a3a22a375ec

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Commit**: PyMedusa/SickRage@c6c6e8412f45c591f4257bd4bceeca84261c2913
**Link to Log**: https://gist.github.com/7c3d5e067d3c829b42b18b196f227a3b
### ERROR
<pre>
2016-09-10 04:51:29 ERROR    SHOWQUEUE-REFRESH :: [c6c6e84] 295767: Error while refreshing show Containment. Error: 'ascii' codec can't encode character u'\xe3' in position 62: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/show_queue.py#L578">sickbeard/show_queue.py</a>", line 578, in run
    self.show.refresh_dir()
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/tv.py#L1256">sickbeard/tv.py</a>", line 1256, in refresh_dir
    self.load_episodes_from_dir()
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/tv.py#L581">sickbeard/tv.py</a>", line 581, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(ek(os.path.join, self.location, media_file))
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/tv.py#L942">sickbeard/tv.py</a>", line 942, in make_ep_from_file
    **********_ep.create_meta_files()
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/tv.py#L2236">sickbeard/tv.py</a>", line 2236, in create_meta_files
    self.__create_nfo()
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/tv.py#L2248">sickbeard/tv.py</a>", line 2248, in __create_nfo
    result = cur_provider.create_episode_metadata(self) or result
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/metadata/generic.py#L259">sickbeard/metadata/generic.py</a>", line 259, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/metadata/generic.py#L457">sickbeard/metadata/generic.py</a>", line 457, in write_ep_file
    nfo_file = io.open(nfo_file_path, 'wb')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 62: ordinal not in range(128)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Commit**: PyMedusa/SickRage@c6c6e8412f45c591f4257bd4bceeca84261c2913
**Link to Log**: https://gist.github.com/b9b012c369e0f4204b5548cc60dfa321
### ERROR
<pre>
2016-09-10 04:37:31 ERROR    SHOWQUEUE-REFRESH :: [c6c6e84] 282670: Error while refreshing show Narcos. Error: 'ascii' codec can't encode character u'\xf3' in position 63: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/show_queue.py#L578">sickbeard/show_queue.py</a>", line 578, in run
    self.show.refresh_dir()
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/tv.py#L1256">sickbeard/tv.py</a>", line 1256, in refresh_dir
    self.load_episodes_from_dir()
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/tv.py#L581">sickbeard/tv.py</a>", line 581, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(ek(os.path.join, self.location, media_file))
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/tv.py#L942">sickbeard/tv.py</a>", line 942, in make_ep_from_file
    **********_ep.create_meta_files()
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/tv.py#L2236">sickbeard/tv.py</a>", line 2236, in create_meta_files
    self.__create_nfo()
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/tv.py#L2248">sickbeard/tv.py</a>", line 2248, in __create_nfo
    result = cur_provider.create_episode_metadata(self) or result
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/metadata/generic.py#L259">sickbeard/metadata/generic.py</a>", line 259, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/metadata/generic.py#L457">sickbeard/metadata/generic.py</a>", line 457, in write_ep_file
    nfo_file = io.open(nfo_file_path, 'wb')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 63: ordinal not in range(128)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@medariox need to use ek in `nfo_file = io.open(nfo_file_path, 'wb')` ?

**Comment by medariox** [comment]
@fernandog 
No, need to set encoding
```nfo_file = io.open(nfo_file_path, 'wb', encoding='utf8')```

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@1fdd694705afae43337fced099f2595575570fae
**Link to Log**: https://gist.github.com/08cd6b82e698be9fc3f3ec3d5b472be0
### ERROR
<pre>
2016-11-02 15:08:00 ERROR    SHOWQUEUE-REFRESH :: [1fdd694] 296069: Error while refreshing show Paul and Nick’s Big American Food Trip. Error: 'ascii' codec can't encode character u'\u2019' in position 33: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/1fdd694705afae43337fced099f2595575570fae/medusa/show_queue.py#L570">medusa/show_queue.py</a>", line 570, in run
    self.show.update_metadata()
  File "/home/home/SickRage/<a href="../blob/1fdd694705afae43337fced099f2595575570fae/medusa/tv.py#L594">medusa/tv.py</a>", line 594, in update_metadata
    self.__update_show_nfo()
  File "/home/home/SickRage/<a href="../blob/1fdd694705afae43337fced099f2595575570fae/medusa/tv.py#L602">medusa/tv.py</a>", line 602, in __update_show_nfo
    result = cur_provider.update_show_indexer_metadata(self) or result
  File "/home/home/SickRage/<a href="../blob/1fdd694705afae43337fced099f2595575570fae/medusa/metadata/generic.py#L279">medusa/metadata/generic.py</a>", line 279, in update_show_indexer_metadata
    showXML.write(nfo_file_path, encoding='UTF-8')
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 802, in write
    file = open(file_or_filename, "wb")
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 33: ordinal not in range(128)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ouraios** [comment]
# Info
Branch: `master`
Commit: `Unknown`
Version: `0.3.4`
Database: `44.14`
Python Version: `2.7.16 (default, May 6 2019, 19:28:45) [GCC 8.3.0]`
SSL Version: `OpenSSL 1.1.1c 28 May 2019`
OS: `Linux-4.15.0-52-generic-x86_64-with`
Locale: `Unknown.Unknown`
Runs in Docker: `Yes`

# Error
```
2019-08-30 02:38:15 WARNING  SHOWQUEUE-ADD :: [] An error occurred while parsing: /torrent/media/tv/One Piece/Season 20/One Piece - S20E08 - Ténèbres de la terre sacrée. Le mystérieux chapeau de paille géant.mp4
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|                   libmediainfo.so.0                   |
|                         v19.4                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/medusa/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/app/medusa/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 60: ordinal not in range(128)
```
