### ISSUE TITLE
[APP SUBMITTED]: no such table: t411

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#584]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.8-3-osmc-armv7l-with-debian-8.4**
Locale: UTF-8
Branch: **pubdate2**
Commit: PyMedusa/SickRage@25756001a9e640bd8a56d85d23d1187372a57824
Link to Log: https://gist.github.com/f9aa4377d42af03175b49c6340583655
### ERROR
```
Thread-16 :: [T411] :: [2575600] DB error: no such table: t411
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/db.py", line 254, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/home/osmc/SickRage/sickbeard/db.py", line 106, in _execute
    sql_results = self.connection.cursor().execute(query)
OperationalError: no such table: t411
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.8-3-osmc-armv7l-with-debian-8.4**
Locale: UTF-8
Branch: **pubdate2**
Commit: PyMedusa/SickRage@25756001a9e640bd8a56d85d23d1187372a57824
Link to Log: https://gist.github.com/d84a1388beedc80282c68d99a1c15585
### ERROR
```
Thread-16 :: [T411] :: [2575600] Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 325, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 1574, in snatchSelection
    show_all_results=show_all_results, **search_show)
  File "/home/osmc/SickRage/sickbeard/manual_search.py", line 235, in get_provider_cache_results
    last_update = main_db_con.select(b"select max(time) as lastupdate from '{provider_id}'".format(provider_id=cur_provider.get_id()))
  File "/home/osmc/SickRage/sickbeard/db.py", line 284, in select
    sql_results = self.action(query, args, fetchall=True)
  File "/home/osmc/SickRage/sickbeard/db.py", line 254, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/home/osmc/SickRage/sickbeard/db.py", line 106, in _execute
    sql_results = self.connection.cursor().execute(query)
OperationalError: no such table: t411
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 325, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 1574, in snatchSelection
    show_all_results=show_all_results, **search_show)
  File "/home/osmc/SickRage/sickbeard/manual_search.py", line 235, in get_provider_cache_results
    last_update = main_db_con.select(b"select max(time) as lastupdate from '{provider_id}'".format(provider_id=cur_provider.get_id()))
  File "/home/osmc/SickRage/sickbeard/db.py", line 284, in select
    sql_results = self.action(query, args, fetchall=True)
  File "/home/osmc/SickRage/sickbeard/db.py", line 254, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/home/osmc/SickRage/sickbeard/db.py", line 106, in _execute
    sql_results = self.connection.cursor().execute(query)
OperationalError: no such table: t411
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
https://github.com/pymedusa/SickRage/pull/578

**Comment by fernandog** [comment]
@p0psicles
