### ISSUE TITLE
[APP SUBMITTED]: invalid literal for int() with base 10: 'None'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#590]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **pubdate2**
Commit: PyMedusa/SickRage@f65f8d7f61dc49e566a12288c8fdfcdb39d312d2
Link to Log: https://gist.github.com/a585df38287e020c7cbf2c4279dba9a5
### ERROR
```
Thread-15 :: [f65f8d7] Failed doing webui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 325, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 1523, in manualSearchCheckCache
    % provider, ["%|" + sql_episode + "|%", season, show, int(last_update)])
ValueError: invalid literal for int() with base 10: 'None'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 325, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 1523, in manualSearchCheckCache
    % provider, ["%|" + sql_episode + "|%", season, show, int(last_update)])
ValueError: invalid literal for int() with base 10: 'None'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **pubdate2**
Commit: PyMedusa/SickRage@f65f8d7f61dc49e566a12288c8fdfcdb39d312d2
Link to Log: https://gist.github.com/de380c8d31b38ce28c18f7c3bbd07a57
### ERROR
```
Thread-16 :: [f65f8d7] Failed doing webui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 325, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 1523, in manualSearchCheckCache
    % provider, ["%|" + sql_episode + "|%", season, show, int(last_update)])
ValueError: invalid literal for int() with base 10: 'None'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/webserve.py", line 325, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/webserve.py", line 1523, in manualSearchCheckCache
    % provider, ["%|" + sql_episode + "|%", season, show, int(last_update)])
ValueError: invalid literal for int() with base 10: 'None'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Hmm still passing None Somewhere instead of 0.

**Comment by fernandog** [comment]
https://github.com/pymedusa/SickRage/pull/578/commits/50aabcaac15a85ec0be7ff4e65aa8ee40714c34e
