### ISSUE TITLE
[APP SUBMITTED]: No JSON object could be decoded

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#639]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@3351698fd0d3b554f0dd6bbd8d0cbee0b60ce128
Link to Log: https://gist.github.com/0f9bcafda8153bec981bf232c004d72e
### ERROR
```
SEARCHQUEUE-MANUAL-311937 :: [TorrentDay] :: [3351698] Unknown exception while searching TorrentDay. Error: 'No JSON object could be decoded'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 547, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 149, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 123, in search
    parsedJSON = self.get_url(self.urls['search'], post_data=post_data, returns='json')
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 356, in get_url
    return getURL(url, post_data, params, self.headers, timeout, self.session, **kwargs)
  File "/home/home/SickRage/sickbeard/helpers.py", line 1472, in getURL
    return resp if response_type == u'response' or response_type is None else resp.json() if response_type == u'json' else getattr(resp, response_type, resp)
  File "/home/home/SickRage/lib/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/home/SickRage/lib/simplejson/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 335, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 353, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@273a600e969733a0bdb7238399f570739e76c64b
Link to Log: https://gist.github.com/f2b86369f6474d23b04bab38c23d704b
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: [273a600] Data returned from provider is not json
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 132, in search
    jdata = response.json()
  File "/home/home/SickRage/lib/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/home/SickRage/lib/simplejson/__init__.py", line 307, in loads
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 335, in decode
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 353, in raw_decode
ValueError: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/f4eb79d209c2cb2624e71417890bb9bb
### ERROR
```
SEARCHQUEUE-BACKLOG-280063 :: [TorrentDay] :: [881d122] Data returned from provider is not json
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 101, in search
    jdata = response.json()
  File "/home/home/SickRage/lib/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/home/SickRage/lib/simplejson/__init__.py", line 307, in loads
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 335, in decode
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 353, in raw_decode
ValueError: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/5f9641f49e582c87f372fc66c1ad27cb
### ERROR
```
SEARCHQUEUE-BACKLOG-268960 :: [TorrentDay] :: [881d122] Data returned from provider is not json
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 101, in search
    jdata = response.json()
  File "/home/home/SickRage/lib/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/home/SickRage/lib/simplejson/__init__.py", line 307, in loads
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 335, in decode
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 353, in raw_decode
ValueError: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/a99e381b3dbafac2d5584cba9dfbc194
### ERROR
```
SEARCHQUEUE-BACKLOG-101501 :: [TorrentDay] :: [881d122] Data returned from provider is not json
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 101, in search
    jdata = response.json()
  File "/home/home/SickRage/lib/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/home/SickRage/lib/simplejson/__init__.py", line 307, in loads
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 335, in decode
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 353, in raw_decode
ValueError: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/49700103fb011364b6d7dbe6cb649a7f
### ERROR
```
SEARCHQUEUE-BACKLOG-77992 :: [TorrentDay] :: [881d122] Data returned from provider is not json
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 101, in search
    jdata = response.json()
  File "/home/home/SickRage/lib/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/home/SickRage/lib/simplejson/__init__.py", line 307, in loads
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 335, in decode
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 353, in raw_decode
ValueError: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/36e2d86fb7fffea981914786c2208a49
### ERROR
```
SEARCHQUEUE-BACKLOG-76372 :: [TorrentDay] :: [881d122] Data returned from provider is not json
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 101, in search
    jdata = response.json()
  File "/home/home/SickRage/lib/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/home/SickRage/lib/simplejson/__init__.py", line 307, in loads
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 335, in decode
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 353, in raw_decode
ValueError: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/70e92cc494e3563bb33b9bf6f3ff8212
### ERROR
```
SEARCHQUEUE-BACKLOG-83755 :: [TorrentDay] :: [881d122] Data returned from provider is not json
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 101, in search
    jdata = response.json()
  File "/home/home/SickRage/lib/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/home/SickRage/lib/simplejson/__init__.py", line 307, in loads
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 335, in decode
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 353, in raw_decode
ValueError: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-78847 :: [TorrentDay] :: [881d122] Data returned from provider is not json
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 101, in search
    jdata = response.json()
  File "/home/home/SickRage/lib/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/home/SickRage/lib/simplejson/__init__.py", line 307, in loads
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 335, in decode
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 353, in raw_decode
ValueError: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-279357 :: [TorrentDay] :: [881d122] Data returned from provider is not json
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 101, in search
    jdata = response.json()
  File "/home/home/SickRage/lib/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/home/SickRage/lib/simplejson/__init__.py", line 307, in loads
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 335, in decode
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 353, in raw_decode
ValueError: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-250793 :: [TorrentDay] :: [881d122] Data returned from provider is not json
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 101, in search
    jdata = response.json()
  File "/home/home/SickRage/lib/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/home/SickRage/lib/simplejson/__init__.py", line 307, in loads
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 335, in decode
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 353, in raw_decode
ValueError: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [TorrentDay] :: [881d122] Data returned from provider is not json
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 101, in search
    jdata = response.json()
  File "/home/home/SickRage/lib/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/home/SickRage/lib/simplejson/__init__.py", line 307, in loads
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 335, in decode
  File "/home/home/SickRage/lib/simplejson/decoder.py", line 353, in raw_decode
ValueError: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
