### ISSUE TITLE
[APP SUBMITTED]: 'unicode' object has no attribute 'raise_for_status'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#650]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@08ed0925599ca0904a7e383aeacf00f6f8e28d3e
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-255775 :: [TorrentDay] :: [08ed092] Unknown exception while searching TorrentDay. Error: "'unicode' object has no attribute 'raise_for_status'"
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 547, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 149, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 126, in search
    response.raise_for_status()
AttributeError: 'unicode' object has no attribute 'raise_for_status'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by labrys** [comment]
@duramato this is the same issue I was discussing in IRC with @medariox
