### ISSUE TITLE
[APP SUBMITTED]: 'str' object has no attribute 'indexerid'

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#667]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.8-7-osmc-armv7l-with-debian-8.5**
Locale: UTF-8
### ERROR
```
Thread-18 :: Failed doing web ui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 265, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/server/web/home/handler.py", line 1531, in updateShow
    return self.redirect('/home/displayShow?show={show}'.format(show=show.indexerid))
AttributeError: 'str' object has no attribute 'indexerid'
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 265, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/server/web/home/handler.py", line 1531, in updateShow
    return self.redirect('/home/displayShow?show={show}'.format(show=show.indexerid))
AttributeError: 'str' object has no attribute 'indexerid'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
6 issues in one issue. looks like wasnt tested

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@eaaf103b4b311ddb851e5da7996ec4317e301439
Link to Log: https://gist.github.com/7c2437f3bd2c632a4d97881b38843979
### ERROR
```
Thread-15 :: [eaaf103] Failed doing web ui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 265, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/server/web/home/handler.py", line 1548, in subtitleShow
    return self.redirect('/home/displayShow?show={show}'.format(show=show.indexerid))
AttributeError: 'str' object has no attribute 'indexerid'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 265, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/server/web/home/handler.py", line 1548, in subtitleShow
    return self.redirect('/home/displayShow?show={show}'.format(show=show.indexerid))
AttributeError: 'str' object has no attribute 'indexerid'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Aah well we did one of the biggest rewrites in two years touching 6 year old legacy webserve code. Bugs are expected.

**Comment by fernandog** [comment]
An IDE will point the error

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@eaaf103b4b311ddb851e5da7996ec4317e301439
Link to Log: https://gist.github.com/36ab0b3d372b1bbbc3008b5c4d14d206
### ERROR
```
Thread-15 :: [eaaf103] Failed doing web ui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 265, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/server/web/home/handler.py", line 1799, in testRename
    'path': 'home/editShow?show={show}'.format(show=show.indexerid),
AttributeError: 'str' object has no attribute 'indexerid'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 265, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/server/web/home/handler.py", line 1799, in testRename
    'path': 'home/editShow?show={show}'.format(show=show.indexerid),
AttributeError: 'str' object has no attribute 'indexerid'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
#671
