### ISSUE TITLE
[APP SUBMITTED]: u'\xed'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#702]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/79acb5f57c271e322e1ac97f489122a3
### ERROR
```
SEARCHQUEUE-BACKLOG-101501 :: [HDSpace] :: [881d122] Unknown exception while searching HDSpace. Error: '\xc3\xad'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 547, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 157, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/hdspace.py", line 95, in search
    search_url = self.urls['search'] % (quote_plus(search_string.replace('.', ' ')),)
  File "/usr/lib/python2.7/urllib.py", line 1293, in quote_plus
    s = quote(s, safe + ' ')
  File "/usr/lib/python2.7/urllib.py", line 1288, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xed'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/fc8dbffa2cbd7a01963b7f426a10ef98
### ERROR
```
SEARCHQUEUE-BACKLOG-101501 :: [SceneTime] :: [881d122] Unknown exception while searching SceneTime. Error: '\xc3\xad'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 547, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 157, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/scenetime.py", line 90, in search
    search_url = self.urls['search'] % (quote(search_string), self.categories)
  File "/usr/lib/python2.7/urllib.py", line 1288, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xed'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed in https://github.com/pymedusa/SickRage/pull/701

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **fixtorrentz2**
Commit: PyMedusa/SickRage@c048786cc1c3b7b6588a67dbc018d69cfabc52be
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-101501 :: [Pretome] :: [c048786] Unknown exception while searching Pretome. Error: '\xc3\xad'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 555, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 185, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrent/html/pretome.py", line 92, in search
    search_url = self.urls['search'] % (quote(search_string), self.categories)
  File "/usr/lib/python2.7/urllib.py", line 1288, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xed'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **fixtorrentz2**
Commit: PyMedusa/SickRage@c048786cc1c3b7b6588a67dbc018d69cfabc52be
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-101501 :: [Pretome] :: [c048786] Unknown exception while searching Pretome. Error: '\xc3\xad'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 555, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 185, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrent/html/pretome.py", line 92, in search
    search_url = self.urls['search'] % (quote(search_string), self.categories)
  File "/usr/lib/python2.7/urllib.py", line 1288, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xed'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
