### ISSUE TITLE
[APP SUBMITTED]: u'\xe1'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#703]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/de9114e70b44f6ec5fec13430454b96c
### ERROR
```
SEARCHQUEUE-BACKLOG-76372 :: [SceneTime] :: [881d122] Unknown exception while searching SceneTime. Error: '\xc3\xa1'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 547, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 157, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/scenetime.py", line 90, in search
    search_url = self.urls['search'] % (quote(search_string), self.categories)
  File "/usr/lib/python2.7/urllib.py", line 1288, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe1'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/d3784afcb71c9c70d882114ebb5bd2c5
### ERROR
```
SEARCHQUEUE-BACKLOG-76372 :: [HDSpace] :: [881d122] Unknown exception while searching HDSpace. Error: '\xc3\xa1'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 547, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 157, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/hdspace.py", line 95, in search
    search_url = self.urls['search'] % (quote_plus(search_string.replace('.', ' ')),)
  File "/usr/lib/python2.7/urllib.py", line 1293, in quote_plus
    s = quote(s, safe + ' ')
  File "/usr/lib/python2.7/urllib.py", line 1288, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe1'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **fixtorrentz2**
Commit: PyMedusa/SickRage@c048786cc1c3b7b6588a67dbc018d69cfabc52be
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-76372 :: [Pretome] :: [c048786] Unknown exception while searching Pretome. Error: '\xc3\xa1'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 555, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 185, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrent/html/pretome.py", line 92, in search
    search_url = self.urls['search'] % (quote(search_string), self.categories)
  File "/usr/lib/python2.7/urllib.py", line 1288, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe1'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
We still have providers with quote? :confused:

**Comment by fernandog** [comment]
@medariox 

torrent/html/scc.py:                search_url = self.urls['search'] % (quote(se                                                                arch_string), self.categories[mode])
torrent/html/pretome.py:                search_url = self.urls['search'] % (quote(search_string), self.categories)

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **fixtorrentz2**
Commit: PyMedusa/SickRage@c048786cc1c3b7b6588a67dbc018d69cfabc52be
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-76372 :: [Pretome] :: [c048786] Unknown exception while searching Pretome. Error: '\xc3\xa1'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 555, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 185, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrent/html/pretome.py", line 92, in search
    search_url = self.urls['search'] % (quote(search_string), self.categories)
  File "/usr/lib/python2.7/urllib.py", line 1288, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe1'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
@fernandog 
Yes, will fix both later today/tomorrow.
