### ISSUE TITLE
UnicodeDecodeError when searching for anime show in Nyaatorrent

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/SickRage#705]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Maybe temporary put back in the UnicodeDecodeError? At least until we've enabled the unicode_literals also in the parser?

Branch/Commit: develop
OS: Windows 7
What you did:
What happened:
What you expected:
Logs:
```
2016-06-20 23:02:47 SEARCHQUEUE-MANUAL-254653 :: [NyaaTorrents] :: [18397ae] Unknown exception while searching NyaaTorrents. Error: u"charmap : \xe3\u0192\ufffd\xe3\u201a\xa4\xe3\u201a\xb9\xe3\u201a\xaf\xe3\u0192\xbc\xe3\u0192\xabD\xc3\u2014D High School DxD (\xe7\u201e\xa1\xe4\xbf\xae\xe6\xad\xa3) - \xe7\xac\xac1\xe6\u0153\u0178+\xe7\xac\xac2\xe6\u0153\u0178(New)+\xe7\xac\xac3\xe6\u0153\u0178(Born) (\xe4\xb9\xb3) (BD - S1280E720 [ABS: [0]] [ANIME VER: 1] [ABD: False] [ANIME: True] [whichReg: ['anime_and_normal_x']] : error 2 : error 3 : character maps to "
Traceback (most recent call last):
  File "D:\Development\ManualSearch\sickbeard\search.py", line 547, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "D:\Development\ManualSearch\sickrage\providers\GenericProvider.py", line 189, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "D:\Development\ManualSearch\sickbeard\name_parser\parser.py", line 467, in parse
    name, file_name_result or dir_name_result))
  File "D:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2: character maps to 
```

**Comment by medariox** [comment]
Is this still an issue?
