### ISSUE TITLE
[APP SUBMITTED]: 'int' object has no attribute 'get'

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#728]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.13-5-osmc-armv7l-with-debian-8.5**
Locale: UTF-8
### ERROR
```
SEARCHQUEUE-BACKLOG-266091 :: [TorrentDay] :: Unknown exception while searching TorrentDay. Error: "'int' object has no attribute 'get'"
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/search.py", line 547, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/osmc/SickRage/sickrage/providers/GenericProvider.py", line 157, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/osmc/SickRage/sickbeard/providers/torrentday.py", line 108, in search
    torrents = jdata.get('Fs', [dict()])[0].get('Cn', {}).get('torrents', [])
AttributeError: 'int' object has no attribute 'get'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Can you reproduce it?

**Comment by fernandog** [comment]
happened in the middle of the night. maybe only one torrent is bad

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@cda3f542d6e4804199300a4761567707c51325bd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-82696 :: [TorrentDay] :: [cda3f54] Unknown exception while searching TorrentDay. Error: "'int' object has no attribute 'get'"
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 552, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 162, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 107, in search
    torrents = jdata.get('Fs', [dict()])[0].get('Cn', {}).get('torrents', [])
AttributeError: 'int' object has no attribute 'get'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@cda3f542d6e4804199300a4761567707c51325bd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-72514 :: [TorrentDay] :: [cda3f54] Unknown exception while searching TorrentDay. Error: "'int' object has no attribute 'get'"
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 552, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 162, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 107, in search
    torrents = jdata.get('Fs', [dict()])[0].get('Cn', {}).get('torrents', [])
AttributeError: 'int' object has no attribute 'get'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@cda3f542d6e4804199300a4761567707c51325bd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-77466 :: [TorrentDay] :: [cda3f54] Unknown exception while searching TorrentDay. Error: "'int' object has no attribute 'get'"
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 552, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 162, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 107, in search
    torrents = jdata.get('Fs', [dict()])[0].get('Cn', {}).get('torrents', [])
AttributeError: 'int' object has no attribute 'get'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@cda3f542d6e4804199300a4761567707c51325bd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-286987 :: [TorrentDay] :: [cda3f54] Unknown exception while searching TorrentDay. Error: "'int' object has no attribute 'get'"
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 552, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 162, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrentday.py", line 107, in search
    torrents = jdata.get('Fs', [dict()])[0].get('Cn', {}).get('torrents', [])
AttributeError: 'int' object has no attribute 'get'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **split-parsing**
Commit: PyMedusa/SickRage@365cec52efa4b72c518ea62a4785cad8a93cb71f
Link to Log: https://gist.github.com/eec6493fcebb90491690a4feee5a119c
### ERROR
```
SEARCHQUEUE-MANUAL-313885 :: [TorrentDay] :: [365cec5] Unknown exception while searching TorrentDay. Error: "'int' object has no attribute 'get'"
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 552, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 181, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrent/json/torrentday.py", line 116, in search
    results += self.parse(jdata, mode)
  File "/home/home/SickRage/sickbeard/providers/torrent/json/torrentday.py", line 132, in parse
    torrent_rows = data.get('Fs', [dict()])[0].get('Cn', {}).get('torrents', [])
AttributeError: 'int' object has no attribute 'get'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **split-parsing**
Commit: PyMedusa/SickRage@365cec52efa4b72c518ea62a4785cad8a93cb71f
Link to Log: https://gist.github.com/f5ed96907c20ea300cd4ffb1a18b0533
### ERROR
```
SEARCHQUEUE-MANUAL-174501 :: [TorrentDay] :: [365cec5] Unknown exception while searching TorrentDay. Error: "'int' object has no attribute 'get'"
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 552, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 181, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrent/json/torrentday.py", line 116, in search
    results += self.parse(jdata, mode)
  File "/home/home/SickRage/sickbeard/providers/torrent/json/torrentday.py", line 132, in parse
    torrent_rows = data.get('Fs', [dict()])[0].get('Cn', {}).get('torrents', [])
AttributeError: 'int' object has no attribute 'get'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
```python
>>> jdata = {u'Fs': [{u'Cn': 0, u'Fn': u'Oarrive'}], u'er': 0}
>>> torrents = jdata.get('Fs', [dict()])[0].get('Cn', {}).get('torrents', [])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'int' object has no attribute 'get'

```

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **split-parsing**
Commit: PyMedusa/SickRage@05d5356005c899d8a6ec0ef905d9092f578063a3
Link to Log: https://gist.github.com/ce398c92ae6d1fb2e5dead2a45f7978b
### ERROR
```
SEARCHQUEUE-MANUAL-76703 :: [TorrentDay] :: [05d5356] Unknown exception while searching TorrentDay. Error: "'int' object has no attribute 'get'"
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 553, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 182, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrent/json/torrentday.py", line 116, in search
    results += self.parse(jdata, mode)
  File "/home/home/SickRage/sickbeard/providers/torrent/json/torrentday.py", line 132, in parse
    torrent_rows = data.get('Fs', [dict()])[0].get('Cn', {}).get('torrents', [])
AttributeError: 'int' object has no attribute 'get'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by labrys** [comment]
Fixed in split-parsing
