### ISSUE TITLE
[APP SUBMITTED]: local variable 'embedded_subtitle_languages' referenced before assignment

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/SickRage#747]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 14:08:17) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **embedded_subs_pp**
Commit: PyMedusa/SickRage@0232f0f9aecb81c8880afff2467849c6da78de1f
Link to Log: https://gist.github.com/59fd8953eaf10fe5850e22cc011a2fba
### ERROR
```
Thread-16 :: [0232f0f] Failed doing web ui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/server/web/home/post_process.py", line 50, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 297, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 569, in process_media
    if not sickbeard.EMBEDDED_SUBTITLES_ALL and sickbeard.EMBEDDED_SUBTITLES_UNKNOWN_LANG and 'und' in has_embedded_subtitles(cur_video_file_path):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 694, in has_embedded_subtitles
    return embedded_subtitle_languages if embedded_subtitle_languages else False
UnboundLocalError: local variable 'embedded_subtitle_languages' referenced before assignment
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/server/web/home/post_process.py", line 50, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 297, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 569, in process_media
    if not sickbeard.EMBEDDED_SUBTITLES_ALL and sickbeard.EMBEDDED_SUBTITLES_UNKNOWN_LANG and 'und' in has_embedded_subtitles(cur_video_file_path):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 694, in has_embedded_subtitles
    return embedded_subtitle_languages if embedded_subtitle_languages else False
UnboundLocalError: local variable 'embedded_subtitle_languages' referenced before assignment
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by NicoLeOca** [comment]
@fernandog 
testing embedded subs branch atm.
I got this issue above

**Comment by fernandog** [comment]
@NicoLeOca fixed

https://github.com/pymedusa/SickRage/pull/743/commits/69757dde3e09454de6a3a2d30a6a2d67bfdb4654

just update
