### ISSUE TITLE
[APP SUBMITTED]: argument of type 'bool' is not iterable

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/SickRage#749]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 14:08:17) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **embedded_subs_pp**
Commit: PyMedusa/SickRage@37a092957378323dac8cc1e806de06698528ed4c
Link to Log: https://gist.github.com/60305501b4ae4e6257cc16f2a878e7a3
### ERROR
```
Thread-16 :: [37a0929] Failed doing web ui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/server/web/home/post_process.py", line 50, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 297, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 569, in process_media
    if not sickbeard.EMBEDDED_SUBTITLES_ALL and sickbeard.EMBEDDED_SUBTITLES_UNKNOWN_LANG and 'und' in has_embedded_subtitles(cur_video_file_path):
TypeError: argument of type 'bool' is not iterable
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/server/web/home/post_process.py", line 50, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 297, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 569, in process_media
    if not sickbeard.EMBEDDED_SUBTITLES_ALL and sickbeard.EMBEDDED_SUBTITLES_UNKNOWN_LANG and 'und' in has_embedded_subtitles(cur_video_file_path):
TypeError: argument of type 'bool' is not iterable
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by NicoLeOca** [comment]
@fernandog 
I updated and I got another for you here

**Comment by fernandog** [comment]
017444b5afa89ca896a30cad97bab1cd9a0732f5
