### ISSUE TITLE
[APP SUBMITTED]: 'list' object has no attribute 'lower'

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#772]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.13-5-osmc-armv7l-with-debian-8.5**
Locale: UTF-8
Branch: **optimized**
Commit: PyMedusa/SickRage@42fd472b258a4c621f98c1c9a4d5d5196338f3ee
Link to Log: https://gist.github.com/de4a9f1120b19ce01abaea0e3b64846a
### ERROR
```
FINDSUBTITLES :: [42fd472] Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/subtitles.py", line 326, in download_best_subs
    for s in subtitles_list], key=operator.itemgetter(1), reverse=True)
  File "/home/osmc/SickRage/lib/subliminal/score.py", line 88, in compute_score
    matches = subtitle.get_matches(video)
  File "/home/osmc/SickRage/lib/subliminal/providers/legendastv.py", line 147, in get_matches
    matches |= guess_matches(video, guessit(self.archive.name, {'type': self.type}))
  File "/home/osmc/SickRage/lib/subliminal/subtitle.py", line 233, in guess_matches
    if video.format and 'format' in guess and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/subtitles.py", line 326, in download_best_subs
    for s in subtitles_list], key=operator.itemgetter(1), reverse=True)
  File "/home/osmc/SickRage/lib/subliminal/score.py", line 88, in compute_score
    matches = subtitle.get_matches(video)
  File "/home/osmc/SickRage/lib/subliminal/providers/legendastv.py", line 147, in get_matches
    matches |= guess_matches(video, guessit(self.archive.name, {'type': self.type}))
  File "/home/osmc/SickRage/lib/subliminal/subtitle.py", line 233, in guess_matches
    if video.format and 'format' in guess and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2 subliminal issue?

**Comment by fernandog** [comment]
@ratoaq2 some how error is happening again. I had 100% sure I tested and it worked
