### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: u'/home/home/SickRage/cache/mako/history.mako.py'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#792]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **split-parsing**
Commit: PyMedusa/SickRage@365cec52efa4b72c518ea62a4785cad8a93cb71f
Link to Log: https://gist.github.com/79a4538c2beef0961efc9ac6d9e1695d
### ERROR
```
Thread-15 :: [365cec5] Failed doing web ui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/server/web/core/history.py", line 44, in index
    topmenu='history', controller='history', action='index')
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 136, in render
    kwargs['backtrace'] = RichTraceback()
  File "/home/home/SickRage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/home/home/SickRage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/home/home/SickRage/lib/mako/template.py", line 640, in code
    return util.read_python_file(self.module_filename)
  File "/home/home/SickRage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/home/home/SickRage/cache/mako/history.mako.py'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/server/web/core/history.py", line 44, in index
    topmenu='history', controller='history', action='index')
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 136, in render
    kwargs['backtrace'] = RichTraceback()
  File "/home/home/SickRage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/home/home/SickRage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/home/home/SickRage/lib/mako/template.py", line 640, in code
    return util.read_python_file(self.module_filename)
  File "/home/home/SickRage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/home/home/SickRage/cache/mako/history.mako.py'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
Getting many of the times i restart/update

**Comment by labrys** [comment]
Couldn't duplicate this.... could you try shutting down Medusa and clearing your cache folder? (you can leave the images subfolder untouched so you don't have to refresh artwork)

**Comment by duramato** [comment]
Medusa clears by itself the mako cache folder on restart,  don't know if its becouse of that

**Comment by labrys** [comment]
Yeah i was just wondering if for some reason yours hadn't cleared it.
