### ISSUE TITLE
[APP SUBMITTED]: 'dict' object has no attribute 'content'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#801]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **split-parsing**
Commit: PyMedusa/SickRage@365cec52efa4b72c518ea62a4785cad8a93cb71f
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-289590 :: [T411] :: [365cec5] Unknown exception while searching T411. Error: "'dict' object has no attribute 'content'"
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 552, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 181, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrent/json/t411.py", line 97, in search
    if not response.content:
AttributeError: 'dict' object has no attribute 'content'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators @labrys

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **split-parsing**
Commit: PyMedusa/SickRage@365cec52efa4b72c518ea62a4785cad8a93cb71f
Link to Log: https://gist.github.com/d158121ad1e742988fb9641ffb2d72ef
### ERROR
```
SEARCHQUEUE-MANUAL-313885 :: [T411] :: [365cec5] Unknown exception while searching T411. Error: "'dict' object has no attribute 'content'"
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 552, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 181, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrent/json/t411.py", line 97, in search
    if not response.content:
AttributeError: 'dict' object has no attribute 'content'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **split-parsing**
Commit: PyMedusa/SickRage@365cec52efa4b72c518ea62a4785cad8a93cb71f
Link to Log: https://gist.github.com/8a147b8817ea6c549c92b374b4783de2
### ERROR
```
SEARCHQUEUE-MANUAL-174501 :: [T411] :: [365cec5] Unknown exception while searching T411. Error: "'dict' object has no attribute 'content'"
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 552, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 181, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/torrent/json/t411.py", line 97, in search
    if not response.content:
AttributeError: 'dict' object has no attribute 'content'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
