### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/home/home/SickRage/cache/mako/tmpSK4uf2'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#814]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **split-parsing**
Commit: PyMedusa/SickRage@51ff7ba22a4b7f2ebb54c6397aab8150049649a8
Link to Log: https://gist.github.com/dc0ae8aba5c4493fd93536ca018b8b52
### ERROR
```
Thread-15 :: [51ff7ba] Failed doing web ui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/server/web/home/handler.py", line 1065, in snatchSelection
    t = PageTemplate(rh=self, filename='snatchSelection.mako')
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/home/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/home/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/home/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/home/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/home/SickRage/lib/mako/template.py", line 711, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python2.7/tempfile.py", line 308, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/home/home/SickRage/cache/mako/tmpSK4uf2'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/server/web/home/handler.py", line 1065, in snatchSelection
    t = PageTemplate(rh=self, filename='snatchSelection.mako')
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/home/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/home/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/home/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/home/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/home/SickRage/lib/mako/template.py", line 711, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python2.7/tempfile.py", line 308, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/home/home/SickRage/cache/mako/tmpSK4uf2'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
Permission?

**Comment by duramato** [comment]
@labrys this happen by going to a manual search page, not a restart. after a refresh the page worked.

**Comment by duramato** [comment]
Another one. This one i don't know what page caused it as i wasn't "greated" with any 404.

```
2016-07-25 09:05:03 Thread-16 :: [51ff7ba] Failed doing web ui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 453, in schedule
    t = PageTemplate(rh=self, filename='schedule.mako')
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/home/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/home/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/home/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/home/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/home/SickRage/lib/mako/template.py", line 711, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python2.7/tempfile.py", line 308, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/home/home/SickRage/cache/mako/tmpU5cy5H'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 453, in schedule
    t = PageTemplate(rh=self, filename='schedule.mako')
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/home/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/home/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/home/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/home/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/home/SickRage/lib/mako/template.py", line 711, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python2.7/tempfile.py", line 308, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/home/home/SickRage/cache/mako/tmpU5cy5H'
```

**Comment by medariox** [comment]
Duplicate https://github.com/pymedusa/SickRage/issues/792
