### ISSUE TITLE
[APP SUBMITTED]: Unterminated control keyword: 'if' in file '/home/osmc/SickRage/gui/slick/views/history.mako' at line: 21 char: 1

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#815]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.13-5-osmc-armv7l-with-debian-8.5**
Locale: UTF-8
Branch: **optimized**
Commit: PyMedusa/SickRage@42fd472b258a4c621f98c1c9a4d5d5196338f3ee
Link to Log: https://gist.github.com/33a0fdb3ed8cbd57a53b5c30efd345b5
### ERROR
```
Thread-20 :: [42fd472] Failed doing web ui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/server/web/core/history.py", line 36, in index
    t = PageTemplate(rh=self, filename='history.mako')
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/osmc/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/osmc/SickRage/lib/mako/template.py", line 700, in _compile_module_file
    generate_magic_comment=True)
  File "/home/osmc/SickRage/lib/mako/template.py", line 665, in _compile
    node = lexer.parse()
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 270, in parse
    self.control_line[-1].pos, self.filename)
SyntaxException: Unterminated control keyword: 'if' in file '/home/osmc/SickRage/gui/slick/views/history.mako' at line: 21 char: 1
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/server/web/core/history.py", line 36, in index
    t = PageTemplate(rh=self, filename='history.mako')
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/osmc/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/osmc/SickRage/lib/mako/template.py", line 700, in _compile_module_file
    generate_magic_comment=True)
  File "/home/osmc/SickRage/lib/mako/template.py", line 665, in _compile
    node = lexer.parse()
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 270, in parse
    self.control_line[-1].pos, self.filename)
SyntaxException: Unterminated control keyword: 'if' in file '/home/osmc/SickRage/gui/slick/views/history.mako' at line: 21 char: 1
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.13-5-osmc-armv7l-with-debian-8.5**
Locale: UTF-8
Branch: **optimized**
Commit: PyMedusa/SickRage@42fd472b258a4c621f98c1c9a4d5d5196338f3ee
Link to Log: https://gist.github.com/252791484b72a0f97f945c56c6055ac0
### ERROR
```
Thread-15 :: [42fd472] Failed doing web ui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/server/web/core/history.py", line 36, in index
    t = PageTemplate(rh=self, filename='history.mako')
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/osmc/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/osmc/SickRage/lib/mako/template.py", line 700, in _compile_module_file
    generate_magic_comment=True)
  File "/home/osmc/SickRage/lib/mako/template.py", line 665, in _compile
    node = lexer.parse()
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 270, in parse
    self.control_line[-1].pos, self.filename)
SyntaxException: Unterminated control keyword: 'if' in file '/home/osmc/SickRage/gui/slick/views/history.mako' at line: 21 char: 1
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/server/web/core/history.py", line 36, in index
    t = PageTemplate(rh=self, filename='history.mako')
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/osmc/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/osmc/SickRage/lib/mako/template.py", line 700, in _compile_module_file
    generate_magic_comment=True)
  File "/home/osmc/SickRage/lib/mako/template.py", line 665, in _compile
    node = lexer.parse()
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 270, in parse
    self.control_line[-1].pos, self.filename)
SyntaxException: Unterminated control keyword: 'if' in file '/home/osmc/SickRage/gui/slick/views/history.mako' at line: 21 char: 1
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.13-5-osmc-armv7l-with-debian-8.5**
Locale: UTF-8
Branch: **optimized**
Commit: PyMedusa/SickRage@42fd472b258a4c621f98c1c9a4d5d5196338f3ee
Link to Log: https://gist.github.com/792d4262bd1406dea23f7ed3b3f9264f
### ERROR
```
Thread-16 :: [42fd472] Failed doing web ui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/server/web/core/history.py", line 36, in index
    t = PageTemplate(rh=self, filename='history.mako')
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/osmc/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/osmc/SickRage/lib/mako/template.py", line 700, in _compile_module_file
    generate_magic_comment=True)
  File "/home/osmc/SickRage/lib/mako/template.py", line 665, in _compile
    node = lexer.parse()
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 270, in parse
    self.control_line[-1].pos, self.filename)
SyntaxException: Unterminated control keyword: 'if' in file '/home/osmc/SickRage/gui/slick/views/history.mako' at line: 21 char: 1
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/server/web/core/history.py", line 36, in index
    t = PageTemplate(rh=self, filename='history.mako')
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/osmc/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/osmc/SickRage/lib/mako/template.py", line 700, in _compile_module_file
    generate_magic_comment=True)
  File "/home/osmc/SickRage/lib/mako/template.py", line 665, in _compile
    node = lexer.parse()
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 270, in parse
    self.control_line[-1].pos, self.filename)
SyntaxException: Unterminated control keyword: 'if' in file '/home/osmc/SickRage/gui/slick/views/history.mako' at line: 21 char: 1
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.13-5-osmc-armv7l-with-debian-8.5**
Locale: UTF-8
Branch: **optimized**
Commit: PyMedusa/SickRage@42fd472b258a4c621f98c1c9a4d5d5196338f3ee
Link to Log: https://gist.github.com/e34cd538ffc4febaabdf857a1e1d8a16
### ERROR
```
Thread-17 :: [42fd472] Failed doing web ui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/server/web/core/history.py", line 36, in index
    t = PageTemplate(rh=self, filename='history.mako')
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/osmc/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/osmc/SickRage/lib/mako/template.py", line 700, in _compile_module_file
    generate_magic_comment=True)
  File "/home/osmc/SickRage/lib/mako/template.py", line 665, in _compile
    node = lexer.parse()
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 270, in parse
    self.control_line[-1].pos, self.filename)
SyntaxException: Unterminated control keyword: 'if' in file '/home/osmc/SickRage/gui/slick/views/history.mako' at line: 21 char: 1
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/server/web/core/history.py", line 36, in index
    t = PageTemplate(rh=self, filename='history.mako')
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/osmc/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/osmc/SickRage/lib/mako/template.py", line 700, in _compile_module_file
    generate_magic_comment=True)
  File "/home/osmc/SickRage/lib/mako/template.py", line 665, in _compile
    node = lexer.parse()
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 270, in parse
    self.control_line[-1].pos, self.filename)
SyntaxException: Unterminated control keyword: 'if' in file '/home/osmc/SickRage/gui/slick/views/history.mako' at line: 21 char: 1
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
