### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /sb_network_timezones/network_timezones.txt (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x699fdbb0>: Failed to establish a new connection: [Errno -2] Nome ou servi\xc3\xa7o desconhecido',))

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#856]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.16-1-osmc-armv7l-with-debian-8.5**
Locale: UTF-8
Branch: **optimized**
Commit: PyMedusa/SickRage@b9d562e3895da931626d9a7a3e0b2a84e42fb559
Link to Log: https://gist.github.com/0add74c932972645ce2043f41f148164
### ERROR
```
DAILYSEARCHER :: [b9d562e] Exception generated in thread DAILYSEARCHER: error HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /sb_network_timezones/network_timezones.txt (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x699fdbb0>: Failed to establish a new connection: [Errno -2] Nome ou servi\xc3\xa7o desconhecido',))
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/scheduler.py", line 106, in run
    self.action.run(self.force)
  File "/home/osmc/SickRage/sickbeard/dailysearcher.py", line 75, in run
    update_network_dict()
  File "/home/osmc/SickRage/sickbeard/network_timezones.py", line 47, in update_network_dict
    url_data = helpers.getURL(url, session=helpers.make_session(), returns='text')
  File "/home/osmc/SickRage/sickbeard/helpers.py", line 1423, in getURL
    verify=verify)
  File "/home/osmc/SickRage/lib/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/osmc/SickRage/lib/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/osmc/SickRage/lib/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/osmc/SickRage/lib/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /sb_network_timezones/network_timezones.txt (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x699fdbb0>: Failed to establish a new connection: [Errno -2] Nome ou servi\xc3\xa7o desconhecido',))
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@pymedusa/developers 
missing to catch this error somehow in helpers.py

in old helpers - before split-parsing - this doesnt happen

**Comment by medariox** [comment]
Needs to be changed to ```returns='response'```.

**Comment by fernandog** [comment]
@medariox happened again.

I sure the issue is in getURL

**Comment by medariox** [comment]
You are still using returns='text'.
