### ISSUE TITLE
[APP SUBMITTED]: global name 'TorrentRSSProvider' is not defined

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/SickRage#861]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10586**
Locale: cp1252
Branch: **develop**
Commit: PyMedusa/SickRage@626c42909bb430dcc7f98b087b80d1b6f48dda5e
Link to Log: https://gist.github.com/9b18d9e2cf14bd1a8787269349e55616
### ERROR
```
Thread-25 :: [626c429] Failed doing web ui callback: Traceback (most recent call last):
  File "C:\Users\rusty\Desktop\pymedusaSickRage\sickbeard\server\web\core\base.py", line 268, in async_call
    result = function(**kwargs)
  File "C:\Users\rusty\Desktop\pymedusaSickRage\sickbeard\server\web\config\providers.py", line 295, in saveProviders
    new_provider = TorrentRSSProvider(cur_name, cur_url, cur_cookies, cur_title_tag)
NameError: global name 'TorrentRSSProvider' is not defined
Traceback (most recent call last):
  File "C:\Users\rusty\Desktop\pymedusaSickRage\sickbeard\server\web\core\base.py", line 268, in async_call
    result = function(**kwargs)
  File "C:\Users\rusty\Desktop\pymedusaSickRage\sickbeard\server\web\config\providers.py", line 295, in saveProviders
    new_provider = TorrentRSSProvider(cur_name, cur_url, cur_cookies, cur_title_tag)
NameError: global name 'TorrentRSSProvider' is not defined
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
all i was trying to do  was add zoogle as a provider. checked it and hit save changes.

**Comment by ripper1967** [comment]
fixed
