### ISSUE TITLE
Error when is looking for Subtitles, manual or automatic

### ISSUE THREAD

**Issue by calvinbr** [pymedusa/SickRage#873]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: OS X
What you did: Tryed to download missing subtitles
What happened: get a error on logs
What you expected: recive the subtitles
Logs:
```
2016-08-10 22:13:26 Thread-16 :: [0554258] Failed to refine video
Traceback (most recent call last):
  File "/Applications/Medusa/lib/subliminal/core.py", line 543, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "/Applications/Medusa/lib/subliminal/refiners/metadata.py", line 32, in refine
    mkv = MKV(f)
  File "/Applications/Medusa/lib/enzyme/mkv.py", line 56, in __init__
    raise MalformedMKVError('Parsing error: %s' % e)
MalformedMKVError: Parsing error: Less than 1 bytes read (0)
2016-08-10 22:12:37 Thread-16 :: [0554258] Unexpected error in provider 'opensubtitles'
Traceback (most recent call last):
  File "/Applications/Medusa/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/Applications/Medusa/lib/subliminal/providers/opensubtitles.py", line 220, in list_subtitles
    query=query, season=season, episode=episode, tag=os.path.basename(video.name))
  File "/Applications/Medusa/lib/subliminal/providers/opensubtitles.py", line 175, in query
    response = checked(self.server.SearchSubtitles(self.token, criteria))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1310, in single_request
    response = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
SSLError: ('The read operation timed out',)
```

**Comment by ratoaq2** [comment]
That happens only with this file? From the logs, it seems that this file is corrupted. Then there's a timeout when searching subtitles in opensubtitles. Is this timeout always happening and only for that file?

**Comment by calvinbr** [comment]
i'm not sure, how can i check with is that? it's possible?

**Comment by ratoaq2** [comment]
First check the file: try to play the file

If you have debug enabled, then you could browse the logs using the logs page and check if the video name logged just before this exception. 
Just need to know if it's a general issue or somewhat related only to that video

**Comment by calvinbr** [comment]
this error is not occurring anymore, i don't know why, could be a problem with my files.
