### ISSUE TITLE
[APP SUBMITTED]: "'type'"

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/SickRage#876]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 14:08:17) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@8ae9bc7c491fc6b98a445afb939412b88aa0fdac
No Log available with ERRORS:
### ERROR
```
FINDSUBTITLES :: [8ae9bc7] Unable to find subtitles for Mr. Robot S02E02. Error: 'type'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 870, in run
    episode_object.download_subtitles()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1759, in download_subtitles
    new_subtitles = subtitles.download_subtitles(self)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 327, in download_subtitles
    logger.error(traceback.format_exc())
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1456, in error
    self.logger.error(msg, *args, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1185, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1278, in _log
    self.handle(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1288, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1328, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 751, in handle
    self.emit(record)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 135, in emit
    message = self.format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 169, in format
    msg = super(CensoredFormatter, self).format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 325, in getMessage
    msg = str(self.msg)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 560, in __str__
    return str(self.fmt).format(*self.args, **self.kwargs)
KeyError: "'type'"
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by NicoLeOca** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 14:08:17) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@8ae9bc7c491fc6b98a445afb939412b88aa0fdac
No Log available with ERRORS:
### ERROR
```
FINDSUBTITLES :: [8ae9bc7] Unable to find subtitles for Mr. Robot S02E01. Error: 'type'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 870, in run
    episode_object.download_subtitles()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1759, in download_subtitles
    new_subtitles = subtitles.download_subtitles(self)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 327, in download_subtitles
    logger.error(traceback.format_exc())
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1456, in error
    self.logger.error(msg, *args, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1185, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1278, in _log
    self.handle(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1288, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1328, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 751, in handle
    self.emit(record)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 135, in emit
    message = self.format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 169, in format
    msg = super(CensoredFormatter, self).format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 325, in getMessage
    msg = str(self.msg)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 560, in __str__
    return str(self.fmt).format(*self.args, **self.kwargs)
KeyError: "'type'"
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2 know whats wrong?

**Comment by ratoaq2** [comment]
@NicoLeOca 
Do you have more debug logs related to this exception?

**Comment by fernandog** [comment]
@NicoLeOca which sub providers enabled?

**Comment by NicoLeOca** [comment]
@fernandog @ratoaq2 

full log containing the error:
https://gist.github.com/NicoLeOca/81e9fc363ca5e1d2fdb96530ebc683d8
last error happened at 19h42.

Subs provider:
thesubdb
opensubtitles
addic7ed
Tvsubtitles

FYI,
Addic7ed give me an error "too many requests" at the moment.
I don't think it's related but the piece of info might be interesting for you

**Comment by fernandog** [comment]
@NicoLeOca please update develop and force find subs for mr. robot again please

**Comment by NicoLeOca** [comment]
@ratoaq2 @fernandog 
updated and subs search forced.
so far so good!
thank you both and well done for your promptness ;-)

**Comment by fernandog** [comment]
@NicoLeOca no issue ? weird. We were expecting another issue.
Can you send full logs again?

**Comment by NicoLeOca** [comment]
lol that's weird indeed

fresh logs:
https://gist.github.com/NicoLeOca/8514210e35a41d60798a1e3d57f91606

there is an issue with the display of the web.
Chrome lost the connection.
the issue appeard with updating to the last commit. (only one commit was available)
is it related? :-/

**Comment by NicoLeOca** [comment]
the issue you expected appeared in the logs:

2016-08-12 21:22:59 SHOWQUEUE-SUBTITLE :: [411ad0d] Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 284, in download_subtitles
    for s in subtitles_list], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/score.py", line 88, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/providers/opensubtitles.py", line 78, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/subtitle.py", line 233, in guess_matches
    if video.format and 'format' in guess and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 284, in download_subtitles
    for s in subtitles_list], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/score.py", line 88, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/providers/opensubtitles.py", line 78, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/subtitle.py", line 233, in guess_matches
    if video.format and 'format' in guess and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'

**Comment by NicoLeOca** [comment]
updated and forced subs
no issue so far 
I waited for the search to be really finished this time
