### ISSUE TITLE
Fail to start on unraid using PhAzE plugin.

### ISSUE THREAD

**Issue by Thraxis** [pymedusa/SickRage#888]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:  Current Develop
OS:  Unraid
What you did:  Tried to start medusa
What happened: It didn't start
What you expected: It to start
Logs:
```
Starting SickRage...
Traceback (most recent call last):
  File "/usr/local/Sickrage/SickBeard.py", line 97, in <module>
    from sickbeard.server.core import SRWebServer
  File "/usr/local/Sickrage/sickbeard/server/core.py", line 17, in <module>
    from sickbeard.server.web import LoginHandler, LogoutHandler, KeyHandler, CalendarHandler
  File "/usr/local/Sickrage/sickbeard/server/web/__init__.py", line 32, in <module>
    from sickbeard.server.web.home import (
  File "/usr/local/Sickrage/sickbeard/server/web/home/__init__.py", line 4, in <module>
    from sickbeard.server.web.home.add_shows import HomeAddShows
  File "/usr/local/Sickrage/sickbeard/server/web/home/add_shows.py", line 25, in <module>
    from sickrage.show.recommendations.anidb import AnidbPopular
  File "/usr/local/Sickrage/sickrage/show/recommendations/anidb.py", line 95, in <module>
    anidb_popular = AnidbPopular()
  File "/usr/local/Sickrage/sickrage/show/recommendations/anidb.py", line 39, in __init__
    self.anidb = Anidb(cache_dir=sickbeard.CACHE_DIR)
  File "/usr/local/Sickrage/lib/simpleanidb/__init__.py", line 39, in __init__
    os.makedirs(self._cache_dir)
  File "/mnt/cache/.PhAzE-Common/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/mnt/cache/.PhAzE-Common/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/.cache'
Start failed: No PID created
```

**Comment by Thraxis** [comment]
A "fix" for this issue is to edit 'Sickrage/sickrage/show/recommendations/anidb.py'

change line 39 from

```
    self.anidb = Anidb(cache_dir=sickbeard.CACHE_DIR)
```

To

```
    if sickbeard.CACHE_DIR:
        self.anidb = Anidb(cache_dir=sickbeard.CACHE_DIR)
```

**Comment by fernandog** [comment]
@p0psicles

**Comment by p0psicles** [comment]
Yeah going to look at this when I have time

**Comment by p0psicles** [comment]
Hmm stange, you apparently don't have a cache folder configured. So then it's trying to use the appsdir lib, to use the users homedir. Which it doesn't have write right to.

Normally on linux/unix it should create a .cache dir in your users home dir. For ex. running as root: /root/.cache/simpleanidb. For some reason, for you it's trying to write it directly in /.cache.

**Comment by ratoaq2** [comment]
Users in Linux might not have a home folder

**Comment by p0psicles** [comment]
I don't get it, if they don't have a sickbeard.CACHE_DIR set, and they don't have a user dir, what can we use for cache? I need to check how come sickbeard.CACHE_DIR is empty?

**Comment by Thraxis** [comment]
my cache_dir in config.ini is defined as follows
```
cache_dir = cache
```

**Comment by Thraxis** [comment]
This is my info from medusa on Master... that work

```
Medusa Configuration
 Medusa Info:	Branch: master
Commit: 0554258fa51fb7bc964527b7b06390ca6c7b48da
Version: v0.1.3
 Python Version:	2.7.10 (default, Jun 26 2015, 16:00:40) [GCC 4.8.2]
 SSL Version:	OpenSSL 1.0.1o 12 Jun 2015
 OS:	Linux-4.1.18-unRAID-x86_64-AMD_C-60_APU_with_Radeon-tm-_HD_Graphics-with-slackware-14.1
 Locale:	en_US.UTF-8
 	 
 	 
 User:	nobody
 Program Folder:	/usr/local/Sickrage
 Config File:	/mnt/cache/appdata/sickrage/config.ini
 Database File:	/mnt/cache/appdata/sickrage/sickbeard.db
 Cache Folder:	/mnt/cache/appdata/sickrage/cache
 Log Folder:	/mnt/cache/appdata/sickrage/Logs
 Arguments:	['--daemon', '--port', '8082', '--datadir', '/mnt/cache/appdata/sickrage', '--pidfile', '/var/run/Sickrage/Sickrage.pid']
```

**Comment by Thraxis** [comment]
And this is the develop branch after adding my fix from above:

```
Medusa Configuration
 Medusa Info:	Branch: develop
Commit: 13ce2b7eaaa2343bbe52c53d6c80dc39bcdfd4a5
Version: v0.1.3
 Python Version:	2.7.10 (default, Jun 26 2015, 16:00:40) [GCC 4.8.2]
 SSL Version:	OpenSSL 1.0.1o 12 Jun 2015
 OS:	Linux-4.1.18-unRAID-x86_64-AMD_C-60_APU_with_Radeon-tm-_HD_Graphics-with-slackware-14.1
 Locale:	en_US.UTF-8
 	 
 	 
 User:	nobody
 Program Folder:	/usr/local/Sickrage
 Config File:	/mnt/cache/appdata/sickrage/config.ini
 Database File:	/mnt/cache/appdata/sickrage/sickbeard.db
 Cache Folder:	/mnt/cache/appdata/sickrage/cache
 Log Folder:	/mnt/cache/appdata/sickrage/Logs
 Arguments:	['--daemon', '--port', '8082', '--datadir', '/mnt/cache/appdata/sickrage', '--pidfile', '/var/run/Sickrage/Sickrage.pid']
 	 
 	 
 Website:	http://github.com/PyMedusa/sickrage.github.io/
 Wiki:	https://github.com/PyMedusa/SickRage/wiki
 Source:	https://github.com/PyMedusa/SickRage/
 IRC Chat:	#pymedusa on irc.freenode.net
```

My only guess is that it is calling that file before the CACHE_DIR is getting set

**Comment by Thraxis** [comment]
Fix was commited to develop
