### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/home/home/SickRage/cache/mako/tmpJcHH04'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#897]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@9ccfb5c56f6600ecaab9c9813c2a74aec5e54db5
Link to Log: https://gist.github.com/113d10be1f9f5ca1287fae4e0175493c
### ERROR
```
Thread-15 :: [9ccfb5c] Failed doing web ui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/server/web/core/history.py", line 36, in index
    t = PageTemplate(rh=self, filename='history.mako')
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/home/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/home/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/home/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/home/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/home/SickRage/lib/mako/template.py", line 711, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python2.7/tempfile.py", line 308, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/home/home/SickRage/cache/mako/tmpJcHH04'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/server/web/core/history.py", line 36, in index
    t = PageTemplate(rh=self, filename='history.mako')
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/home/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/home/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/home/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/home/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/home/SickRage/lib/mako/template.py", line 711, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python2.7/tempfile.py", line 308, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/home/home/SickRage/cache/mako/tmpJcHH04'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Same issue as #922.
