### ISSUE TITLE
Regular warning from Opensubtitles

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/SickRage#915]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: last develop
OS: Synology last DSM
What you did: I keep having this warning in the logs on a regular basis
What happened:
What you expected:
Logs:
```
2016-08-18 11:37:10 FINDSUBTITLES :: [d9aa711] Unexpected error in provider 'opensubtitles'
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 68, in __getitem__
    provider.initialize()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/providers/opensubtitles.py", line 138, in initialize
    'subliminal v%s' % __short_version__))
  File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1310, in single_request
    response = h.getresponse(buffering=True)
  File "/usr/local/python/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/local/python/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/python/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/python/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/usr/local/python/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
SSLError: ('The read operation timed out',)
```
full logs
https://gist.github.com/NicoLeOca/de74d92159165301e6c84ab11c3c4c68

**Comment by ratoaq2** [comment]
The fulllogs shows 2 errors (HTTP 500) when searhing for subtitles for this episode:
`Animal Kingdom US Season 01 Episode 10`

Can you confirm if that's happening only to this episode or to any other episode?

**Comment by NicoLeOca** [comment]
@ratoaq2 
I had the same error for another episode same show and also for another show:

2016-08-16 05:05:34 DEBUG    FINDSUBTITLES :: [8afc0ce] Checking subtitle candidates for 2 Broke Girls S05E02 (2.Broke.Girls.S05E02.1080p.WEB-DL.DD5.1.H.264.mkv)
2016-08-16 05:05:34 DEBUG    FINDSUBTITLES :: [8afc0ce] Found cached video information under key sickbeard.subtitles:video|/volume1/Download Syno/dst/Seedbox/2.Broke.Girls.S05E02.1080p.WEB-DL.DD5.1.H.264.mkv
2016-08-16 05:05:34 DEBUG    FINDSUBTITLES :: [8afc0ce] Creating a new ProviderPool instance
2016-08-16 05:05:34 DEBUG    FINDSUBTITLES :: [8afc0ce] Listing subtitles with provider 'thesubdb' and languages set([<Language [en]>])
2016-08-16 05:05:34 DEBUG    FINDSUBTITLES :: [8afc0ce] Initializing provider thesubdb
2016-08-16 05:05:34 DEBUG    FINDSUBTITLES :: [8afc0ce] Searching subtitles {'action': 'search', 'hash': 'c83b8235a5929f3fd92be31e6c1b2d21'}
2016-08-16 05:05:34 DEBUG    FINDSUBTITLES :: [8afc0ce] No subtitles found
2016-08-16 05:05:35 DEBUG    FINDSUBTITLES :: [8afc0ce] Listing subtitles with provider 'opensubtitles' and languages set([<Language [en]>])
2016-08-16 05:05:35 DEBUG    FINDSUBTITLES :: [8afc0ce] Initializing provider opensubtitles
2016-08-16 05:05:35 DEBUG    FINDSUBTITLES :: [8afc0ce] Logging in
2016-08-16 05:05:35 WARNING  FINDSUBTITLES :: [8afc0ce] Unexpected error in provider 'opensubtitles'
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 68, in __getitem__
    provider.initialize()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/providers/opensubtitles.py", line 138, in initialize
    'subliminal v%s' % __short_version__))
  File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1328, in single_request
    response.msg,
ProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 500 Internal Server Error>

**Comment by fernandog** [comment]
i guess you are using an outdate openssl 

Have you ever downloaded a sub from opensubtitle? or never?

**Comment by fernandog** [comment]
@NicoLeOca send a print of Medusa info page exameple: `localhost:8081/config`

**Comment by NicoLeOca** [comment]
![opensubs](https://cloud.githubusercontent.com/assets/9487685/17785601/b45c3b44-6581-11e6-8988-958e27a711d9.JPG)
![openssl](https://cloud.githubusercontent.com/assets/9487685/17785605/b6ce336e-6581-11e6-980e-a834b58920f6.JPG)

also see version

**Comment by medariox** [comment]
I almost always get some of these with downloaded shows, until today I
thought they were only being shown with the subliminal logs enabled - seems
I was wrong? I noticed that the most erroneous providers are Opensubtitles,
Addic7ed and Shooters. Anyway, aren't these all upstream issues?

**Comment by fernandog** [comment]
i think its the outdated openssl. Its from Dec 2015.

mine is: OpenSSL 1.0.1t 3 May 2016

**Comment by fernandog** [comment]
@NicoLeOca disable subliminal logs in medusa setting for now

**Comment by NicoLeOca** [comment]
@fernandog 
done
is it a new feature? I didn't see it before

**Comment by ratoaq2** [comment]
Subliminal logs were not part of medusa logs and it was hard to troubleshoot subtitles issues. Since April these logs are there. But there's currently a discussion of when errors/warnings should bother the user. A site being offline or unstable is indeed an issue but not our application issue. Should the user be aware of it? How should we handle these cases that there's nothing to be fixed  in our side? Should we keep the detailed information in the logs and do not warn the user? Or the other way? 

Just raising these points

**Comment by NicoLeOca** [comment]
I'd rather keep the setting and set it unchecked by default.

**Comment by medariox** [comment]
@NicoLeOca 
Not sure why they were enabled for you, but subs logging is already disabled by default.
