### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: u'/home/home/SickRage/cache/mako/layouts/main.mako.py'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#922]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@ecf647e774c9ce1e77f9a07e33e53738bfe9a270
Link to Log: https://gist.github.com/69d6318144064ddd22a2ca09b042aef4
### ERROR
```
Thread-15 :: [ecf647e] Failed doing web ui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 271, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/server/web/home/add_shows.py", line 330, in popularShows
    controller="addShows", action="recommendedShows")
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 139, in render
    kwargs['backtrace'] = RichTraceback()
  File "/home/home/SickRage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/home/home/SickRage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/home/home/SickRage/lib/mako/template.py", line 640, in code
    return util.read_python_file(self.module_filename)
  File "/home/home/SickRage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/home/home/SickRage/cache/mako/layouts/main.mako.py'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 271, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/sickbeard/server/web/home/add_shows.py", line 330, in popularShows
    controller="addShows", action="recommendedShows")
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 139, in render
    kwargs['backtrace'] = RichTraceback()
  File "/home/home/SickRage/lib/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/home/home/SickRage/lib/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/home/home/SickRage/lib/mako/template.py", line 640, in code
    return util.read_python_file(self.module_filename)
  File "/home/home/SickRage/lib/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/home/home/SickRage/cache/mako/layouts/main.mako.py'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
This is getting bonkers, it got to a point i couldn't use tons of pages.

**Comment by fernandog** [comment]
@duramato i still think its a permission issue. check all your foldes permissions/owner

**Comment by duramato** [comment]
```
drwxr-xr-x  2 home home 4.0K Aug 19 10:47 backup
drwxr-xr-x  3 home home 4.0K Aug 19 11:17 cache
-rw-r--r--  1 home home  81M Aug 19 12:00 cache.db
-rw-r--r--  1 home home  34K Aug 19 11:16 config.ini
drwxrwxr-x  3 home home 4.0K Jul 15 23:55 contrib
-rw-r--r--  1 home home 2.5K Aug 14 19:50 CONTRIBUTING.md
-rw-rw-r--  1 home home  35K Jul 15 23:55 COPYING.txt
-rw-r--r--  1 home home 106K Aug 19 09:04 failed.db
drwxrwxr-x  3 home home 4.0K Jul 15 23:55 gui
drwxrwxr-x 58 home home 4.0K Aug 14 19:50 lib
drwxr-xr-x  2 home home 4.0K Aug 19 12:00 Logs
-rw-r--r--  1 home home 1.2K Aug 18 23:14 package.json
-rw-r--r--  1 home home  18K Aug 15 16:36 pytest.ini
-rw-rw-r--  1 home home 4.0K Jul 15 23:55 readme.md
drwxrwxr-x  2 home home 4.0K Jul 15 23:55 runscripts
-rw-r--r--  1 home home 1012 Aug 14 19:50 setup.py
drwxrwxr-x 11 home home 4.0K Aug 18 12:18 sickbeard
-rw-r--r--  1 home home  19M Aug 19 12:00 sickbeard.db
-rw-r--r--  1 home home  24K Jul 16 00:17 sickbeard.db.v42
-rw-r--r--  1 home home  24K Jul 16 00:17 sickbeard.db.v42.1
-rwxr-xr-x  1 home home  22K Jul 16 16:45 SickBeard.py
drwxrwxr-x  9 home home 4.0K Jul 16 00:17 sickrage
drwxrwxr-x  4 home home 4.0K Aug 15 20:17 tests
-rw-r--r--  1 home home  456 Aug 14 19:50 tox.ini
```

```
~/SickRage/cache$ ls -lh
total 1016K
-rw-r--r-- 1 home home 993K Aug 17 15:23 anime-list.xml
drwxr-xr-x 6 home home  20K Aug 19 10:56 images
```

**Comment by OmgImAlexis** [comment]
@duramato these are my permissions on a clean install with everything working. Straight away I noticed your `lib` has different permissions.

```
-rw-r--r--   1 xo staff 2.5K Aug 19 12:12 CONTRIBUTING.md
-rw-r--r--   1 xo staff  35K Jul 30 13:33 COPYING.txt
drwxr-xr-x   3 xo staff  102 Jul 30 15:11 Logs
-rwxr-xr-x   1 xo staff  22K Aug 19 12:11 SickBeard.py
drwxr-xr-x   3 xo staff  102 Aug 19 12:11 backup
drwxr-xr-x   3 xo staff  102 Aug 19 22:11 cache
-rw-r--r--   1 xo staff 256K Aug 19 18:03 cache.db
-rw-r--r--   1 xo staff  26K Aug 19 22:11 config.ini
drwxr-xr-x   4 xo staff  136 Jul 30 13:33 contrib
-rw-r--r--   1 xo staff  16K Jul 30 15:12 failed.db
drwxr-xr-x   3 xo staff  102 Jul 30 13:33 gui
drwxr-xr-x  85 xo staff 2.9K Aug 19 12:13 lib
-rw-r--r--   1 xo staff 1.2K Aug 19 12:12 package.json
-rw-r--r--   1 xo staff  18K Aug 19 12:12 pytest.ini
-rw-r--r--   1 xo staff 4.0K Jul 30 13:34 readme.md
drwxr-xr-x  10 xo staff  340 Jul 30 13:34 runscripts
-rw-r--r--   1 xo staff 1012 Aug 19 12:12 setup.py
drwxr-xr-x 105 xo staff 3.5K Aug 19 12:13 sickbeard
-rw-r--r--   1 xo staff  88K Aug 19 15:04 sickbeard.db
-rw-r--r--   1 xo staff  80K Jul 30 15:12 sickbeard.db.v42
-rw-r--r--   1 xo staff  80K Jul 30 15:12 sickbeard.db.v42.1
drwxr-xr-x  11 xo staff  374 Jul 30 15:11 sickrage
drwxr-xr-x  37 xo staff 1.3K Aug 19 12:12 tests
-rw-r--r--   1 xo staff  456 Aug 19 12:12 tox.ini
```

**Comment by duramato** [comment]
It has more permissions but i wouldn't expect that to interfere, or am i wrong?

**Comment by fernandog** [comment]
@duramato which user is running medusa?

**Comment by duramato** [comment]
home

**Comment by fernandog** [comment]
i have no idea. as you said before a new install works.

**Comment by medariox** [comment]
Tried to delete all cache?

**Comment by duramato** [comment]
Yes i did tried that before @medariox

**Comment by medariox** [comment]
Is it possible that your HDD is very busy and your I/O extremely slow? It
could be that it just can't keep up with the processed code, expecting
files that don't exist yet. Yes, if that's the case, we should probably
handle that *somehow*.

**Comment by fernandog** [comment]
still an issue? if no, close please
