### ISSUE TITLE
Snatch failed because of notifications timed out (Trakt)

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#928]
@p0psicles @ratoaq2 

snatch failed because of timeout!
it didnt updated DB and the torrent is in the client
as ep is in backlog (not preferred quality) it sill snatch again as status is still WANTED

```
2016-08-19 19:01:16 DEBUG    SNATCHQUEUE-MANUALSNATCH-247808 :: [f3ebd83] Adding Suits S06E06 to Trakt watchlist
2016-08-19 19:01:46 DEBUG    SNATCHQUEUE-MANUALSNATCH-247808 :: [f3ebd83] Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/search_queue.py", line 412, in run
    self.success = search.snatchEpisode(search_result)
  File "/home/osmc/SickRage/sickbeard/search.py", line 198, in snatchEpisode
    notifiers.trakt_notifier.update_watchlist(result.show, data_episode=data_episode, update="add")
  File "/home/osmc/SickRage/sickbeard/notifiers/trakt.py", line 186, in update_watchlist
    trakt_api.request(trakt_url, data, method='POST')
  File "/home/osmc/SickRage/lib/traktor/trakt.py", line 113, in request
    data=data, verify=self.ssl_verify)
  File "/home/osmc/SickRage/lib/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/osmc/SickRage/lib/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/osmc/SickRage/lib/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=30)

```

**Comment by fernandog** [comment]
@p0psicles until you handle exceptions in trakt, I added this commit 84b59ebab7fe0a2d43fbd32f8198bf4c7515d430
