### ISSUE TITLE
[APP SUBMITTED]: index() got an unexpected keyword argument 'traktList'

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#931]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.16-1-osmc-armv7l-with-debian-8.5**
Locale: UTF-8
Branch: **optimized**
Commit: PyMedusa/SickRage@f3ebd83c2c263ea7406e35dffabebf52d1dbab58
Link to Log: https://gist.github.com/a81ee15348f15d75cb1cb404d6f47f11
### ERROR
```
Thread-15 :: [f3ebd83] Failed doing web ui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 271, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument 'traktList'
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 271, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument 'traktList'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@p0psicles

**Comment by fernandog** [comment]
@xo i think is JS issue:


when opened recommended list the url is: https://localhost:8081/addShows/trendingShows/?traktList=anticipated

when i change "Select Trakt List" to - example - "popular" URL becomes: https://localhost:8081/?traktList=popular

and when I full refresh i get error
