### ISSUE TITLE
Findsubtitles Error

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/SickRage#944]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: develop
Commit: f59fac368a899993125e6a27ebad08367f396464
OS: Synology DSM

2016-08-21 13:22:24 FINDSUBTITLES :: [f59fac3] Exception generated in thread FINDSUBTITLES: level must be an integer
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 106, in run
    self.action.run(self.force)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 745, in run
    self.subtitles_download_in_pp()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 680, in subtitles_download_in_pp
    tv_episode = TVEpisode.from_filepath(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1706, in from_filepath
    logger.log(logger.INFO, u'Cannot create TVEpisode from path {path}'.format(path=filepath))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 630, in log
    _globals.instance.log(*args, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 351, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1219, in log
    raise TypeError("level must be an integer")
TypeError: level must be an integer

full logs:
https://gist.github.com/NicoLeOca/08381f745c86effc5cc62ced935b2e60

**Comment by fernandog** [comment]
@ratoaq2

**Comment by NicoLeOca** [comment]
@fernandog 

is that the same issue?

2016-09-04 10:57:41 WARNING  FINDSUBTITLES :: [81dd9b4] Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 299, in download_subtitles
    single=not sickbeard.SUBTITLES_MULTI)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 695, in save_subtitles
    with io.open(subtitle_path, 'wb') as f:
IOError: [Errno 2] No such file or directory: '/volume1/Download Syno/dst/Seedbox/2.Broke.Girls.S05E19.1080p.HDTV.X264-DIMENSION[rarbg]/2.Broke.Girls.S05E19.1080p.HDTV.X264-DIMENSION.en.srt'

**Comment by fernandog** [comment]
no. its trying to save a subtitles to a folder that doesnt exist
