### ISSUE TITLE
Failed doing web ui callback: Traceback (most recent call last):

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#947]
### INFO
**Python Version**: `2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.16-1-osmc-armv7l-with-debian-8.5`
**Locale**: `UTF-8`
**Branch**: `optimized`
**Commit**: PyMedusa/SickRage@1aaab79f6550711e398e1851765d24b0cb71dba8
**Link to Log**: https://gist.github.com/1a802df8387252810ad3f1859c7f3f09
### ERROR
```
2016-08-21 13:14:42,784 ERROR    Thread-15 :: [1aaab79] Failed doing web ui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 269, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/server/web/core/history.py", line 36, in index
    t = PageTemplate(rh=self, filename='history.mako')
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/osmc/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/osmc/SickRage/lib/mako/template.py", line 700, in _compile_module_file
    generate_magic_comment=True)
  File "/home/osmc/SickRage/lib/mako/template.py", line 665, in _compile
    node = lexer.parse()
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 270, in parse
    self.control_line[-1].pos, self.filename)
SyntaxException: Unterminated control keyword: 'if' in file '/home/osmc/SickRage/gui/slick/views/history.mako' at line: 18 char: 1
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 269, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/server/web/core/history.py", line 36, in index
    t = PageTemplate(rh=self, filename='history.mako')
  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 69, in __init__
    self.template = lookup.get_template(filename)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/osmc/SickRage/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/osmc/SickRage/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/osmc/SickRage/lib/mako/template.py", line 700, in _compile_module_file
    generate_magic_comment=True)
  File "/home/osmc/SickRage/lib/mako/template.py", line 665, in _compile
    node = lexer.parse()
  File "/home/osmc/SickRage/lib/mako/lexer.py", line 270, in parse
    self.control_line[-1].pos, self.filename)
SyntaxException: Unterminated control keyword: 'if' in file '/home/osmc/SickRage/gui/slick/views/history.mako' at line: 18 char: 1
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2 issue title should be: `SyntaxException: Unterminated control keyword: 'if' in file '/home/osmc/SickRage/gui/slick/views/history.mako' at line: 18 char: 1` right?
