### ISSUE TITLE
ReadTimeout: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=30)

### ISSUE THREAD

**Issue by ratoaq2** [pymedusa/SickRage#954]
### INFO
**Python Version**: `2.7.11 (default, Jan  5 2016, 18:57:05) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.77-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: `feature/improved-issue-submission`
**Commit**: PyMedusa/SickRage@d25fdabca2385f62ad6959ca190dcbd1d9070648
**Link to Log**: https://gist.github.com/6d5ed1c1125323af85a583fce40e415d
### ERROR
```
2016-08-22 15:57:53,585 ERROR    TRAKTCHECKER :: [d25fdab] Unknown Trakt request exception. Code error: None
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/traktor/trakt.py", line 113, in request
    data=data, verify=self.ssl_verify)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=30)
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2 maybe we are forgetting to check one HTTP status code?

**Comment by ratoaq2** [comment]
No... read timeout is a timeout, you don't get any response code since you don't get the response

**Comment by ratoaq2** [comment]
The timeout shouldn't create an error that users could submit. Probably it should be a warning

**Comment by fernandog** [comment]
Is it breaking flow?

It shows as error becase of traktor logger so we can find out what we need to proper catch in exceptions or new HTTP status code
