### ISSUE TITLE
NameError: global name 'tv' is not defined

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#958]
### INFO
**Python Version**: `2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.16-1-osmc-armv7l-with-debian-8.5`
**Locale**: `UTF-8`
**Branch**: `optimized`
**Commit**: PyMedusa/SickRage@9e3d237686029b1afdbef6027156755b3fb0620e
**Link to Log**: https://gist.github.com/ccbb1ccd561ae8a95c21ad458a7c9e8c
### ERROR
```
2016-08-22 20:33:13 ERROR    FINDSUBTITLES :: [9e3d237] Exception generated in thread FINDSUBTITLES: global name 'tv' is not defined
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/scheduler.py", line 106, in run
    self.action.run(self.force)
  File "/home/osmc/SickRage/sickbeard/subtitles.py", line 746, in run
    self.subtitles_download_in_pp()
  File "/home/osmc/SickRage/sickbeard/subtitles.py", line 693, in subtitles_download_in_pp
    tv.episode.release_name = ''
NameError: global name 'tv' is not defined
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
Testing issue
