### ISSUE TITLE
[APP SUBMITTED]: don't know how to handle UnicodeDecodeError in error callback

### ISSUE THREAD

**Issue by Eiber** [pymedusa/SickRage#961]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **develop**
Commit: PyMedusa/SickRage@9eeb3b514b81e359f958d7e3a15f28c053aa8372
Link to Log: https://gist.github.com/490e7eac084a0477f472dd088dcfcf97
### ERROR
```
Thread-15 :: [9eeb3b5] Failed doing web ui callback: Traceback (most recent call last):
  File "C:\Users\Kevin van Deursen\Desktop\SickRage-develop\sickbeard\server\web\core\base.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\Users\Kevin van Deursen\Desktop\SickRage-develop\sickbeard\server\web\home\post_process.py", line 50, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type, ignore_subs=argToBool(ignore_subs)
  File "C:\Users\Kevin van Deursen\Desktop\SickRage-develop\sickbeard\processTV.py", line 263, in processDir
    for curDir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]:
  File "C:\Users\Kevin van Deursen\Desktop\SickRage-develop\sickbeard\processTV.py", line 411, in validateDir
    NameParser().parse(video, cache_result=False)
  File "C:\Users\Kevin van Deursen\Desktop\SickRage-develop\sickbeard\name_parser\parser.py", line 241, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result).decode('utf-8', 'xmlcharrefreplace'))
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: don't know how to handle UnicodeDecodeError in error callback
Traceback (most recent call last):
  File "C:\Users\Kevin van Deursen\Desktop\SickRage-develop\sickbeard\server\web\core\base.py", line 270, in async_call
    result = function(**kwargs)
  File "C:\Users\Kevin van Deursen\Desktop\SickRage-develop\sickbeard\server\web\home\post_process.py", line 50, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type, ignore_subs=argToBool(ignore_subs)
  File "C:\Users\Kevin van Deursen\Desktop\SickRage-develop\sickbeard\processTV.py", line 263, in processDir
    for curDir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]:
  File "C:\Users\Kevin van Deursen\Desktop\SickRage-develop\sickbeard\processTV.py", line 411, in validateDir
    NameParser().parse(video, cache_result=False)
  File "C:\Users\Kevin van Deursen\Desktop\SickRage-develop\sickbeard\name_parser\parser.py", line 241, in parse
    logger.debug('Parsed {name} into {result}', name=name, result=str(result).decode('utf-8', 'xmlcharrefreplace'))
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: don't know how to handle UnicodeDecodeError in error callback
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2 @medariox

**Comment by Eiber** [comment]
Manual post-process is broken. Was working fine a few days ago. Automatic post-process hasn't run yet so don't know if this is working..

**Comment by fernandog** [comment]
@Eiber filename has special chars on it ?

**Comment by Eiber** [comment]
Release name of tv show: Marvel's.Agent.Carter.S01E01.Pilot.1080p.WEB-DL.DD5.1.H.264-Coo7

**Comment by fernandog** [comment]
is it inside any folder?

**Comment by Eiber** [comment]
When removing the ' wrong the filename postproces is working fine

**Comment by fernandog** [comment]
are you running with `python.exe` or `pythonw.exe` ?
looks like if failed because a log line and not the PP code itself

**Comment by Eiber** [comment]
Running on python.exe.. Will try on python.exe

**Comment by duramato** [comment]
`logger.debug('Parsed {name} into {result}', name=name, result=str(result).decode('utf-8', 'xmlcharrefreplace'))`

May be the `xmlcharrefreplace` part

**Comment by Eiber** [comment]
@fernandog: same error on python.exe

**Comment by fernandog** [comment]
i bet is the "str(result)"

@Eiber can you change `SickRage/sickbeard/name_parser/parser.py` line 499 to:

`logger.debug('Parsed {name} into {result}', name=name, result=result.decode('utf-8', 'xmlcharrefreplace'))`

**Comment by Eiber** [comment]
There's nothing at line 499. Suggested line is on 241 but when with that change I get error: object has no attribute 'decode'

**Comment by fernandog** [comment]
@Eiber my fault sorry. need to think about it

**Comment by ratoaq2** [comment]
Could you change L241 to

`logger.debug('Parsed {name} into {result}', name=name, result=str(result))`

and try with the same problematic file?

**Comment by Eiber** [comment]
That fixes the issue!
