### ISSUE TITLE
[APP SUBMITTED]: _log() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#975]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@b152c03b7b98d20e03c1cdf5d7169f256f77e2d1
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [b152c03] Exception generated in thread FINDPROPERS: _log() got an unexpected keyword argument 'name'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/scheduler.py", line 106, in run
    self.action.run(self.force)
  File "/home/home/SickRage/sickbeard/properFinder.py", line 66, in run
    propers = self._get_proper_results()
  File "/home/home/SickRage/sickbeard/properFinder.py", line 181, in _get_proper_results
    parse_result = NameParser().parse(cur_proper.name)
  File "/home/home/SickRage/sickbeard/name_parser/parser.py", line 235, in parse
    result = self._parse_string(name)
  File "/home/home/SickRage/sickbeard/name_parser/parser.py", line 121, in _parse_string
    air_date=result.air_date, name=show.name)
  File "/usr/lib/python2.7/logging/__init__.py", line 1164, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'name'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@duramato can you PR?

air_date=result.air_date, name=show.name)

Insread of name use show_name
